parameters:
    netgen_block_manager.collection.result_builder.class: Netgen\BlockManager\Collection\Result\ResultBuilder
    netgen_block_manager.collection.registry.query_type.class: Netgen\BlockManager\Collection\Registry\QueryTypeRegistry

services:
    netgen_block_manager.collection.result_builder:
        class: "%netgen_block_manager.collection.result_builder.class%"
        arguments:
            - "@netgen_block_manager.item.item_builder"

    netgen_block_manager.collection.registry.query_type:
        class: "%netgen_block_manager.collection.registry.query_type.class%"
