default_view_templates:
    layout_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layouts:layout.html.twig'
    rule_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layout_resolver:rule.html.twig'
    rule_target_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layout_resolver/target:target.html.twig'
        value: 'NetgenBlockManagerAdminBundle:admin/layout_resolver/target/value:target.html.twig'
    rule_condition_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layout_resolver/condition:condition.html.twig'
        value: 'NetgenBlockManagerAdminBundle:admin/layout_resolver/condition/value:condition.html.twig'
