default_view_templates:
    layout_info_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layouts:layout.html.twig'
    rule_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layout_resolver:rule.html.twig'
    rule_target_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layout_resolver/target:target.html.twig'
    rule_condition_view:
        admin: 'NetgenBlockManagerAdminBundle:admin/layout_resolver/condition:condition.html.twig'
