view:
    form_view:
        api:
            layout\create:
                template: "NetgenBlockManagerAdminBundle:app/form/layout:create.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Form\CreateType
            block\full_edit:
                template: "NetgenBlockManagerAdminBundle:app/form/block/edit:full.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\FullEditType
            block\content_edit:
                template: "NetgenBlockManagerAdminBundle:app/form/block/edit:content.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\ContentEditType
            block\design_edit\list:
                template: "NetgenBlockManagerAdminBundle:app/form/block/edit/design:list.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\DesignEditType
                    form\block\definition: list
            block\design_edit\gallery:
                template: "NetgenBlockManagerAdminBundle:app/form/block/edit/design:gallery.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\DesignEditType
                    form\block\definition: gallery
            block\design_edit:
                template: "NetgenBlockManagerAdminBundle:app/form/block/edit:design.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\DesignEditType
            query\full_edit:
                template: "NetgenBlockManagerAdminBundle:app/form/query/edit:full.html.twig"
                match:
                    form\type: Netgen\BlockManager\Collection\Query\Form\FullEditType
        admin:
            condition\type:
                template: "NetgenBlockManagerAdminBundle:admin/form/layout_resolver:condition_type.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Resolver\Form\ConditionType
            target\type:
                template: "NetgenBlockManagerAdminBundle:admin/form/layout_resolver:target_type.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Resolver\Form\TargetType
