view:
    layout_view:
        admin:
            layout\shared:
                template: "@NetgenBlockManagerAdmin/admin/shared_layouts/layout.html.twig"
                match:
                    layout\shared: true
