view:
    rule_condition_view:
        admin:
            route_parameter:
                template: "NetgenBlockManagerAdminBundle:admin/layout_resolver/condition:route_parameter.html.twig"
                match:
                    rule_condition\type: route_parameter
