ngbm_admin_layouts_index:
    path: /
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:index"

ngbm_admin_layouts_layout_copy:
    path: /{layoutId}/copy
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:copyLayout"

ngbm_admin_layouts_layout_delete:
    path: /{layoutId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:deleteLayout"

ngbm_admin_layouts_cache:
    path: /{layoutId}/cache
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:clearLayoutCache"
        _ngbm_status: published

ngbm_admin_layouts_cache_blocks:
    path: /{layoutId}/cache/blocks
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:clearBlocksCache"
        _ngbm_status: published
