ngbm_admin_layout_resolver_index:
    path: /
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:index"

ngbm_admin_layout_resolver_rule_create:
    path: /rules
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:createRule"

ngbm_admin_layout_resolver_rule_update_prorities:
    path: /rules/priorities
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:updatePriorities"

ngbm_admin_layout_resolver_rule_update:
    path: /rules/{ruleId}
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:updateRule"
        _ngbm_status: draft

ngbm_admin_layout_resolver_rule_enable:
    path: /rules/{ruleId}/enable
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:enableRule"
        _ngbm_status: published

ngbm_admin_layout_resolver_rule_disable:
    path: /rules/{ruleId}/disable
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:disableRule"
        _ngbm_status: published

ngbm_admin_layout_resolver_rule_create_draft:
    path: /rules/{ruleId}/draft
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:createRuleDraft"
        _ngbm_status: published

ngbm_admin_layout_resolver_rule_discard:
    path: /rules/{ruleId}/discard
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:discardRuleDraft"
        _ngbm_status: draft

ngbm_admin_layout_resolver_rule_publish:
    path: /rules/{ruleId}/publish
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:publishRuleDraft"
        _ngbm_status: draft

ngbm_admin_layout_resolver_rule_delete:
    path: /rules/{ruleId}/delete
    methods: [GET, DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:deleteRule"
        _ngbm_status: published

ngbm_admin_layout_resolver_target_form_create:
    path: /rules/{ruleId}/target/new/{type}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:targetCreateForm"
        _ngbm_status: draft

ngbm_admin_layout_resolver_target_form_edit:
    path: /targets/{targetId}/edit
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:targetEditForm"
        _ngbm_status: draft

ngbm_admin_layout_resolver_target_delete:
    path: /targets/{targetId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:deleteTarget"
        _ngbm_status: draft

ngbm_admin_layout_resolver_condition_form_create:
    path: /rules/{ruleId}/condition/new/{type}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:conditionCreateForm"
        _ngbm_status: draft

ngbm_admin_layout_resolver_condition_form_edit:
    path: /conditions/{conditionId}/edit
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:conditionEditForm"
        _ngbm_status: draft

ngbm_admin_layout_resolver_condition_delete:
    path: /conditions/{conditionId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layout_resolver:deleteCondition"
        _ngbm_status: draft
