ngbm_admin_layouts_index:
    path: /
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:index"

ngbm_admin_layouts_layout_delete:
    path: /{layoutId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:deleteLayout"
