# Redirect routes that redirect base paths like /layout_resolver to /layout_resolver/
# Specified in order to keep the context (e.g. siteaccess in eZ Publish)
# which is otherwise lost with automatic redirect in RedirectableUrlMatcher
# since it uses urlRedirect action of Redirect controller.
# See: https://github.com/symfony/symfony/issues/12141

_ngbm_admin_no_slash:
    path: /admin
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin
        permanent: true

ngbm_admin_layout_resolver_index_no_slash:
    path: /admin/layout_resolver
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layout_resolver_index
        permanent: true

ngbm_admin_layouts_index_no_slash:
    path: /admin/layouts
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layouts_index
        permanent: true

ngbm_admin_shared_layouts_index_no_slash:
    path: /admin/shared_layouts
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_shared_layouts_index
        permanent: true
