ngbm_admin_shared_layouts_index:
    path: /
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.admin.shared_layouts:index"

ngbm_admin_shared_layouts_layout_copy:
    path: /{layoutId}/copy
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:copyLayout"

ngbm_admin_shared_layouts_layout_delete:
    path: /{layoutId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:deleteLayout"

ngbm_admin_shared_layouts_cache:
    path: /cache
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:clearLayoutsCache"
        _ngbm_status: published

ngbm_admin_shared_layouts_cache_blocks:
    path: /{layoutId}/cache/blocks
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.admin.layouts:clearBlocksCache"
        _ngbm_status: published

ngbm_admin_shared_layouts_cache_related_layouts:
    path: /{layoutId}/cache/related_layouts
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.admin.shared_layouts:clearRelatedLayoutsCache"
        _ngbm_status: published
