view:
    layout_view:
        default:
            4_zones_a:
                template: "@NetgenBlockManagerFixtures/layout/4_zones_a.html.twig"
                match:
                    layout\type: 4_zones_a
            4_zones_b:
                template: "@NetgenBlockManagerFixtures/layout/4_zones_b.html.twig"
                match:
                    layout\type: 4_zones_b
        api:
            4_zones_a:
                template: "@NetgenBlockManagerFixtures/api/layout/4_zones_a.html.twig"
                match:
                    layout\type: 4_zones_a
                    api_version: 1
            4_zones_b:
                template: "@NetgenBlockManagerFixtures/api/layout/4_zones_b.html.twig"
                match:
                    layout\type: 4_zones_b
                    api_version: 1
