services:
    netgen_block_manager.persistence.doctrine.transaction_handler:
        class: Netgen\BlockManager\Persistence\Doctrine\TransactionHandler
        public: false
        arguments:
            - "@database_connection"

    # Persistence helpers

    netgen_block_manager.persistence.doctrine.helper.connection:
        class: Netgen\BlockManager\Persistence\Doctrine\Helper\ConnectionHelper
        public: false
        arguments:
            - "@database_connection"

    netgen_block_manager.persistence.doctrine.helper.position:
        class: Netgen\BlockManager\Persistence\Doctrine\Helper\PositionHelper
        public: false
        arguments:
            - "@database_connection"

    # Layout related persistence APIs

    netgen_block_manager.persistence.doctrine.layout.query_handler:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutQueryHandler
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.layout.mapper:
        class: Netgen\BlockManager\Persistence\Doctrine\Mapper\LayoutMapper
        public: false

    netgen_block_manager.persistence.doctrine.layout.handler:
        class: Netgen\BlockManager\Persistence\Doctrine\Handler\LayoutHandler
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.layout.query_handler"
            - "@netgen_block_manager.persistence.doctrine.block.handler"
            - "@netgen_block_manager.persistence.doctrine.layout.mapper"

    # Block related persistence APIs

    netgen_block_manager.persistence.doctrine.block.query_handler:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\BlockQueryHandler
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.block.mapper:
        class: Netgen\BlockManager\Persistence\Doctrine\Mapper\BlockMapper
        public: false

    netgen_block_manager.persistence.doctrine.block.handler:
        class: Netgen\BlockManager\Persistence\Doctrine\Handler\BlockHandler
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.block.query_handler"
            - "@netgen_block_manager.persistence.doctrine.collection.handler"
            - "@netgen_block_manager.persistence.doctrine.block.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.position"

    # Collection related persistence APIs

    netgen_block_manager.persistence.doctrine.collection.query_handler:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\CollectionQueryHandler
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.collection.mapper:
        class: Netgen\BlockManager\Persistence\Doctrine\Mapper\CollectionMapper
        public: false

    netgen_block_manager.persistence.doctrine.collection.handler:
        class: Netgen\BlockManager\Persistence\Doctrine\Handler\CollectionHandler
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.collection.query_handler"
            - "@netgen_block_manager.persistence.doctrine.collection.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.position"

    # Layout resolver related persistence APIs

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolverQueryHandler
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"
            - []

    netgen_block_manager.persistence.doctrine.layout_resolver.mapper:
        class: Netgen\BlockManager\Persistence\Doctrine\Mapper\LayoutResolverMapper
        public: false

    netgen_block_manager.persistence.doctrine.layout_resolver.handler:
        class: Netgen\BlockManager\Persistence\Doctrine\Handler\LayoutResolverHandler
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.layout_resolver.query_handler"
            - "@netgen_block_manager.persistence.doctrine.layout_resolver.mapper"

    # Layout related APIs

    netgen_block_manager.core.validator.layout:
        class: Netgen\BlockManager\Core\Validator\LayoutValidator
        public: false
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.mapper.layout:
        class: Netgen\BlockManager\Core\Mapper\LayoutMapper
        public: false
        arguments:
            - "@netgen_block_manager.persistence.layout.handler"
            - "@netgen_block_manager.layout.registry.layout_type"

    netgen_block_manager.core.struct_builder.layout:
        class: Netgen\BlockManager\Core\StructBuilder\LayoutStructBuilder
        public: false

    netgen_block_manager.core.service.layout:
        class: Netgen\BlockManager\Core\Service\LayoutService
        public: false
        arguments:
            - "@netgen_block_manager.persistence.transaction_handler"
            - "@netgen_block_manager.core.validator.layout"
            - "@netgen_block_manager.core.mapper.layout"
            - "@netgen_block_manager.core.struct_builder.layout"
            - "@netgen_block_manager.persistence.layout.handler"

    # Block related APIs

    netgen_block_manager.core.validator.block:
        class: Netgen\BlockManager\Core\Validator\BlockValidator
        public: false
        arguments:
            - "@netgen_block_manager.core.validator.collection"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.mapper.block:
        class: Netgen\BlockManager\Core\Mapper\BlockMapper
        public: false
        arguments:
            - "@netgen_block_manager.persistence.block.handler"
            - "@netgen_block_manager.persistence.collection.handler"
            - "@netgen_block_manager.core.mapper.collection"
            - "@netgen_block_manager.core.mapper.parameter"
            - "@netgen_block_manager.core.mapper.config"
            - "@netgen_block_manager.block.registry.block_definition"

    netgen_block_manager.core.struct_builder.block:
        class: Netgen\BlockManager\Core\StructBuilder\BlockStructBuilder
        public: false
        arguments:
            - "@netgen_block_manager.core.struct_builder.config"

    netgen_block_manager.core.service.block:
        class: Netgen\BlockManager\Core\Service\BlockService
        public: false
        arguments:
            - "@netgen_block_manager.persistence.transaction_handler"
            - "@netgen_block_manager.core.validator.block"
            - "@netgen_block_manager.core.mapper.block"
            - "@netgen_block_manager.core.struct_builder.block"
            - "@netgen_block_manager.core.mapper.parameter"
            - "@netgen_block_manager.core.mapper.config"
            - "@netgen_block_manager.core.service.layout"
            - "@netgen_block_manager.persistence.block.handler"
            - "@netgen_block_manager.persistence.layout.handler"
            - "@netgen_block_manager.persistence.collection.handler"

    # Collection related APIs

    netgen_block_manager.core.validator.collection:
        class: Netgen\BlockManager\Core\Validator\CollectionValidator
        public: false
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.mapper.collection:
        class: Netgen\BlockManager\Core\Mapper\CollectionMapper
        public: false
        arguments:
            - "@netgen_block_manager.persistence.collection.handler"
            - "@netgen_block_manager.core.mapper.parameter"
            - "@netgen_block_manager.core.mapper.config"
            - "@netgen_block_manager.collection.registry.item_definition"
            - "@netgen_block_manager.collection.registry.query_type"
            - "@netgen_block_manager.item.item_loader"

    netgen_block_manager.core.struct_builder.collection:
        class: Netgen\BlockManager\Core\StructBuilder\CollectionStructBuilder
        public: false
        arguments:
            - "@netgen_block_manager.core.struct_builder.config"

    netgen_block_manager.core.service.collection:
        class: Netgen\BlockManager\Core\Service\CollectionService
        public: false
        arguments:
            - "@netgen_block_manager.persistence.transaction_handler"
            - "@netgen_block_manager.core.validator.collection"
            - "@netgen_block_manager.core.mapper.collection"
            - "@netgen_block_manager.core.struct_builder.collection"
            - "@netgen_block_manager.core.mapper.parameter"
            - "@netgen_block_manager.core.mapper.config"
            - "@netgen_block_manager.persistence.collection.handler"

    # Layout resolver related APIs

    netgen_block_manager.core.validator.layout_resolver:
        class: Netgen\BlockManager\Core\Validator\LayoutResolverValidator
        public: false
        arguments:
            - "@netgen_block_manager.layout.resolver.registry.target_type"
            - "@netgen_block_manager.layout.resolver.registry.condition_type"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.mapper.layout_resolver:
        class: Netgen\BlockManager\Core\Mapper\LayoutResolverMapper
        public: false
        arguments:
            - "@netgen_block_manager.persistence.layout_resolver.handler"
            - "@netgen_block_manager.layout.resolver.registry.target_type"
            - "@netgen_block_manager.layout.resolver.registry.condition_type"
            - "@netgen_block_manager.core.service.layout"

    netgen_block_manager.core.struct_builder.layout_resolver:
        class: Netgen\BlockManager\Core\StructBuilder\LayoutResolverStructBuilder
        public: false

    netgen_block_manager.core.service.layout_resolver:
        class: Netgen\BlockManager\Core\Service\LayoutResolverService
        public: false
        arguments:
            - "@netgen_block_manager.persistence.transaction_handler"
            - "@netgen_block_manager.core.validator.layout_resolver"
            - "@netgen_block_manager.core.mapper.layout_resolver"
            - "@netgen_block_manager.core.struct_builder.layout_resolver"
            - "@netgen_block_manager.persistence.layout_resolver.handler"
            - "@netgen_block_manager.persistence.layout.handler"

    # Config API services

    netgen_block_manager.core.struct_builder.config:
        class: Netgen\BlockManager\Core\StructBuilder\ConfigStructBuilder
        public: false

    netgen_block_manager.core.mapper.config:
        class: Netgen\BlockManager\Core\Mapper\ConfigMapper
        public: false
        arguments:
            - "@netgen_block_manager.core.mapper.parameter"

    # Parameter API services

    netgen_block_manager.core.mapper.parameter:
        class: Netgen\BlockManager\Core\Mapper\ParameterMapper
        public: false

    # Service aliases

    netgen_block_manager.api.service.layout:
        alias: netgen_block_manager.core.service.layout
        public: true

    netgen_block_manager.api.service.block:
        alias: netgen_block_manager.core.service.block
        public: true

    netgen_block_manager.api.service.collection:
        alias: netgen_block_manager.core.service.collection
        public: true

    netgen_block_manager.api.service.layout_resolver:
        alias: netgen_block_manager.core.service.layout_resolver
        public: true

    netgen_block_manager.persistence.transaction_handler:
        alias: netgen_block_manager.persistence.doctrine.transaction_handler
        public: false

    netgen_block_manager.persistence.layout.handler:
        alias: netgen_block_manager.persistence.doctrine.layout.handler
        public: false

    netgen_block_manager.persistence.block.handler:
        alias: netgen_block_manager.persistence.doctrine.block.handler
        public: false

    netgen_block_manager.persistence.collection.handler:
        alias: netgen_block_manager.persistence.doctrine.collection.handler
        public: false

    netgen_block_manager.persistence.layout_resolver.handler:
        alias: netgen_block_manager.persistence.doctrine.layout_resolver.handler
        public: false
