parameters:
    netgen_block_manager.persistence.doctrine.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler
    netgen_block_manager.persistence.doctrine.helper.connection.class: Netgen\BlockManager\Persistence\Doctrine\Helper\ConnectionHelper
    netgen_block_manager.persistence.doctrine.helper.position.class: Netgen\BlockManager\Persistence\Doctrine\Helper\PositionHelper
    netgen_block_manager.persistence.doctrine.helper.query.class: Netgen\BlockManager\Persistence\Doctrine\Helper\QueryHelper

    netgen_block_manager.persistence.doctrine.layout.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\LayoutMapper
    netgen_block_manager.persistence.doctrine.layout.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\LayoutHandler

    netgen_block_manager.persistence.doctrine.block.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\BlockMapper
    netgen_block_manager.persistence.doctrine.block.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\BlockHandler

    netgen_block_manager.persistence.doctrine.collection.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\CollectionMapper
    netgen_block_manager.persistence.doctrine.collection.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\CollectionHandler

    netgen_block_manager.core.repository.class: Netgen\BlockManager\Core\Repository

    netgen_block_manager.core.service.layout.validator.class: Netgen\BlockManager\Core\Service\Validator\LayoutValidator
    netgen_block_manager.core.service.layout.mapper.class: Netgen\BlockManager\Core\Service\Mapper\LayoutMapper
    netgen_block_manager.core.service.layout.class: Netgen\BlockManager\Core\Service\LayoutService

    netgen_block_manager.core.service.block.validator.class: Netgen\BlockManager\Core\Service\Validator\BlockValidator
    netgen_block_manager.core.service.block.mapper.class: Netgen\BlockManager\Core\Service\Mapper\BlockMapper
    netgen_block_manager.core.service.block.class: Netgen\BlockManager\Core\Service\BlockService

    netgen_block_manager.core.service.collection.validator.class: Netgen\BlockManager\Core\Service\Validator\CollectionValidator
    netgen_block_manager.core.service.collection.mapper.class: Netgen\BlockManager\Core\Service\Mapper\CollectionMapper
    netgen_block_manager.core.service.collection.class: Netgen\BlockManager\Core\Service\CollectionService

services:
    netgen_block_manager.persistence.doctrine.handler:
        class: "%netgen_block_manager.persistence.doctrine.handler.class%"
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.layout.handler"
            - "@netgen_block_manager.persistence.doctrine.block.handler"
            - "@netgen_block_manager.persistence.doctrine.collection.handler"

    # Layout related persistence APIs

    netgen_block_manager.persistence.doctrine.helper.connection:
        class: "%netgen_block_manager.persistence.doctrine.helper.connection.class%"
        arguments:
            - "@database_connection"

    netgen_block_manager.persistence.doctrine.helper.position:
        class: "%netgen_block_manager.persistence.doctrine.helper.position.class%"
        arguments:
            - "@database_connection"

    netgen_block_manager.persistence.doctrine.helper.query:
        class: "%netgen_block_manager.persistence.doctrine.helper.query.class%"
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.layout.mapper:
        class: "%netgen_block_manager.persistence.doctrine.layout.mapper.class%"

    netgen_block_manager.persistence.doctrine.layout.handler:
        class: "%netgen_block_manager.persistence.doctrine.layout.handler.class%"
        arguments:
            - "@netgen_block_manager.persistence.doctrine.block.handler"
            - "@netgen_block_manager.persistence.doctrine.collection.handler"
            - "@netgen_block_manager.persistence.doctrine.layout.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"
            - "@netgen_block_manager.persistence.doctrine.helper.query"

    netgen_block_manager.persistence.doctrine.block.mapper:
        class: "%netgen_block_manager.persistence.doctrine.block.mapper.class%"

    netgen_block_manager.persistence.doctrine.block.handler:
        class: "%netgen_block_manager.persistence.doctrine.block.handler.class%"
        arguments:
            - "@netgen_block_manager.persistence.doctrine.collection.handler"
            - "@netgen_block_manager.persistence.doctrine.block.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"
            - "@netgen_block_manager.persistence.doctrine.helper.position"
            - "@netgen_block_manager.persistence.doctrine.helper.query"

    netgen_block_manager.persistence.doctrine.collection.mapper:
        class: "%netgen_block_manager.persistence.doctrine.collection.mapper.class%"

    netgen_block_manager.persistence.doctrine.collection.handler:
        class: "%netgen_block_manager.persistence.doctrine.collection.handler.class%"
        arguments:
            - "@netgen_block_manager.persistence.doctrine.collection.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"
            - "@netgen_block_manager.persistence.doctrine.helper.position"
            - "@netgen_block_manager.persistence.doctrine.helper.query"

    netgen_block_manager.core.repository:
        class: "%netgen_block_manager.core.repository.class%"
        arguments:
            - "@netgen_block_manager.core.service.layout"
            - "@netgen_block_manager.core.service.block"
            - "@netgen_block_manager.core.service.collection"
            - "@netgen_block_manager.persistence.doctrine.handler"

    # Layout related APIs

    netgen_block_manager.core.service.layout.validator:
        class: "%netgen_block_manager.core.service.layout.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.layout.mapper:
        class: "%netgen_block_manager.core.service.layout.mapper.class%"
        arguments:
            - "@netgen_block_manager.core.service.block.mapper"
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.layout:
        class: "%netgen_block_manager.core.service.layout.class%"
        arguments:
            - "@netgen_block_manager.core.service.layout.validator"
            - "@netgen_block_manager.core.service.layout.mapper"
            - "@netgen_block_manager.persistence.handler"

    # Block related APIs

    netgen_block_manager.core.service.block.validator:
        class: "%netgen_block_manager.core.service.block.validator.class%"
        arguments:
            - "@netgen_block_manager.block_definition.registry"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.block.mapper:
        class: "%netgen_block_manager.core.service.block.mapper.class%"
        arguments:
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.block:
        class: "%netgen_block_manager.core.service.block.class%"
        arguments:
            - "@netgen_block_manager.core.service.block.validator"
            - "@netgen_block_manager.core.service.block.mapper"
            - "@netgen_block_manager.persistence.handler"

    # Collection related APIs

    netgen_block_manager.core.service.collection.validator:
        class: "%netgen_block_manager.core.service.collection.validator.class%"
        arguments:
            - "@netgen_block_manager.collection.query_type.registry"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.collection.mapper:
        class: "%netgen_block_manager.core.service.collection.mapper.class%"
        arguments:
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.collection:
        class: "%netgen_block_manager.core.service.collection.class%"
        arguments:
            - "@netgen_block_manager.core.service.collection.validator"
            - "@netgen_block_manager.core.service.collection.mapper"
            - "@netgen_block_manager.persistence.handler"

    # Service aliases

    netgen_block_manager.api.repository:
        alias: netgen_block_manager.core.repository

    netgen_block_manager.api.service.layout:
        alias: netgen_block_manager.core.service.layout

    netgen_block_manager.api.service.block:
        alias: netgen_block_manager.core.service.block

    netgen_block_manager.api.service.collection:
        alias: netgen_block_manager.core.service.collection

    netgen_block_manager.persistence.handler:
        alias: netgen_block_manager.persistence.doctrine.handler
