parameters:
    netgen_block_manager.persistence.doctrine.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler
    netgen_block_manager.persistence.doctrine.helper.connection.class: Netgen\BlockManager\Persistence\Doctrine\Helper\ConnectionHelper
    netgen_block_manager.persistence.doctrine.helper.position.class: Netgen\BlockManager\Persistence\Doctrine\Helper\PositionHelper

    netgen_block_manager.persistence.doctrine.layout.query_handler.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutQueryHandler
    netgen_block_manager.persistence.doctrine.layout.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\LayoutMapper
    netgen_block_manager.persistence.doctrine.layout.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\LayoutHandler

    netgen_block_manager.persistence.doctrine.block.query_handler.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\BlockQueryHandler
    netgen_block_manager.persistence.doctrine.block.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\BlockMapper
    netgen_block_manager.persistence.doctrine.block.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\BlockHandler

    netgen_block_manager.persistence.doctrine.collection.query_handler.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\CollectionQueryHandler
    netgen_block_manager.persistence.doctrine.collection.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\CollectionMapper
    netgen_block_manager.persistence.doctrine.collection.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\CollectionHandler

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolverQueryHandler
    netgen_block_manager.persistence.doctrine.layout_resolver.mapper.class: Netgen\BlockManager\Persistence\Doctrine\Mapper\LayoutResolverMapper
    netgen_block_manager.persistence.doctrine.layout_resolver.handler.class: Netgen\BlockManager\Persistence\Doctrine\Handler\LayoutResolverHandler

    netgen_block_manager.core.repository.class: Netgen\BlockManager\Core\Repository

    netgen_block_manager.core.service.layout.validator.class: Netgen\BlockManager\Core\Service\Validator\LayoutValidator
    netgen_block_manager.core.service.layout.mapper.class: Netgen\BlockManager\Core\Service\Mapper\LayoutMapper
    netgen_block_manager.core.service.layout.class: Netgen\BlockManager\Core\Service\LayoutService

    netgen_block_manager.core.service.block.validator.class: Netgen\BlockManager\Core\Service\Validator\BlockValidator
    netgen_block_manager.core.service.block.mapper.class: Netgen\BlockManager\Core\Service\Mapper\BlockMapper
    netgen_block_manager.core.service.block.class: Netgen\BlockManager\Core\Service\BlockService

    netgen_block_manager.core.service.collection.validator.class: Netgen\BlockManager\Core\Service\Validator\CollectionValidator
    netgen_block_manager.core.service.collection.mapper.class: Netgen\BlockManager\Core\Service\Mapper\CollectionMapper
    netgen_block_manager.core.service.collection.class: Netgen\BlockManager\Core\Service\CollectionService

    netgen_block_manager.core.service.layout_resolver.validator.class: Netgen\BlockManager\Core\Service\Validator\LayoutResolverValidator
    netgen_block_manager.core.service.layout_resolver.mapper.class: Netgen\BlockManager\Core\Service\Mapper\LayoutResolverMapper
    netgen_block_manager.core.service.layout_resolver.class: Netgen\BlockManager\Core\Service\LayoutResolverService

services:
    netgen_block_manager.persistence.doctrine.handler:
        class: "%netgen_block_manager.persistence.doctrine.handler.class%"
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.layout.handler"
            - "@netgen_block_manager.persistence.doctrine.block.handler"
            - "@netgen_block_manager.persistence.doctrine.collection.handler"
            - "@netgen_block_manager.persistence.doctrine.layout_resolver.handler"

    # Persistence helpers

    netgen_block_manager.persistence.doctrine.helper.connection:
        class: "%netgen_block_manager.persistence.doctrine.helper.connection.class%"
        public: false
        arguments:
            - "@database_connection"

    netgen_block_manager.persistence.doctrine.helper.position:
        class: "%netgen_block_manager.persistence.doctrine.helper.position.class%"
        public: false
        arguments:
            - "@database_connection"

    # Layout related persistence APIs

    netgen_block_manager.persistence.doctrine.layout.query_handler:
        class: "%netgen_block_manager.persistence.doctrine.layout.query_handler.class%"
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.layout.mapper:
        class: "%netgen_block_manager.persistence.doctrine.layout.mapper.class%"
        public: false

    netgen_block_manager.persistence.doctrine.layout.handler:
        class: "%netgen_block_manager.persistence.doctrine.layout.handler.class%"
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.layout.query_handler"
            - "@netgen_block_manager.persistence.doctrine.block.query_handler"
            - "@netgen_block_manager.persistence.doctrine.block.handler"
            - "@netgen_block_manager.persistence.doctrine.collection.handler"
            - "@netgen_block_manager.persistence.doctrine.layout.mapper"

    # Block related persistence APIs

    netgen_block_manager.persistence.doctrine.block.query_handler:
        class: "%netgen_block_manager.persistence.doctrine.block.query_handler.class%"
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.block.mapper:
        class: "%netgen_block_manager.persistence.doctrine.block.mapper.class%"
        public: false

    netgen_block_manager.persistence.doctrine.block.handler:
        class: "%netgen_block_manager.persistence.doctrine.block.handler.class%"
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.block.query_handler"
            - "@netgen_block_manager.persistence.doctrine.collection.handler"
            - "@netgen_block_manager.persistence.doctrine.block.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.position"

    # Collection related persistence APIs

    netgen_block_manager.persistence.doctrine.collection.query_handler:
        class: "%netgen_block_manager.persistence.doctrine.collection.query_handler.class%"
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"

    netgen_block_manager.persistence.doctrine.collection.mapper:
        class: "%netgen_block_manager.persistence.doctrine.collection.mapper.class%"
        public: false

    netgen_block_manager.persistence.doctrine.collection.handler:
        class: "%netgen_block_manager.persistence.doctrine.collection.handler.class%"
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.collection.query_handler"
            - "@netgen_block_manager.persistence.doctrine.collection.mapper"
            - "@netgen_block_manager.persistence.doctrine.helper.position"

    # Layout resolver related persistence APIs

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.class%"
        public: false
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.helper.connection"
            - []

    netgen_block_manager.persistence.doctrine.layout_resolver.mapper:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.mapper.class%"
        public: false

    netgen_block_manager.persistence.doctrine.layout_resolver.handler:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.handler.class%"
        public: false
        arguments:
            - "@netgen_block_manager.persistence.doctrine.layout_resolver.query_handler"
            - "@netgen_block_manager.persistence.doctrine.layout_resolver.mapper"

    # Repository

    netgen_block_manager.core.repository:
        class: "%netgen_block_manager.core.repository.class%"
        arguments:
            - "@netgen_block_manager.core.service.layout"
            - "@netgen_block_manager.core.service.block"
            - "@netgen_block_manager.core.service.collection"
            - "@netgen_block_manager.core.service.layout_resolver"
            - "@netgen_block_manager.persistence.doctrine.handler"

    # Layout related APIs

    netgen_block_manager.core.service.layout.validator:
        class: "%netgen_block_manager.core.service.layout.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.layout.mapper:
        class: "%netgen_block_manager.core.service.layout.mapper.class%"
        arguments:
            - "@netgen_block_manager.core.service.block.mapper"
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.layout:
        class: "%netgen_block_manager.core.service.layout.class%"
        arguments:
            - "@netgen_block_manager.core.service.layout.validator"
            - "@netgen_block_manager.core.service.layout.mapper"
            - "@netgen_block_manager.persistence.handler"
            - "@netgen_block_manager.configuration.registry.layout_type"

    # Block related APIs

    netgen_block_manager.core.service.block.validator:
        class: "%netgen_block_manager.core.service.block.validator.class%"
        arguments:
            - "@netgen_block_manager.block.registry.block_definition"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.block.mapper:
        class: "%netgen_block_manager.core.service.block.mapper.class%"
        arguments:
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.block:
        class: "%netgen_block_manager.core.service.block.class%"
        arguments:
            - "@netgen_block_manager.core.service.block.validator"
            - "@netgen_block_manager.core.service.block.mapper"
            - "@netgen_block_manager.persistence.handler"
            - "@netgen_block_manager.configuration.registry.layout_type"
            - "@netgen_block_manager.block.registry.block_definition"

    # Collection related APIs

    netgen_block_manager.core.service.collection.validator:
        class: "%netgen_block_manager.core.service.collection.validator.class%"
        arguments:
            - "@netgen_block_manager.collection.registry.query_type"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.collection.mapper:
        class: "%netgen_block_manager.core.service.collection.mapper.class%"
        arguments:
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.collection:
        class: "%netgen_block_manager.core.service.collection.class%"
        arguments:
            - "@netgen_block_manager.core.service.collection.validator"
            - "@netgen_block_manager.core.service.collection.mapper"
            - "@netgen_block_manager.persistence.handler"

    # Layout resolver related APIs

    netgen_block_manager.core.service.layout_resolver.validator:
        class: "%netgen_block_manager.core.service.layout_resolver.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.core.service.layout_resolver.mapper:
        class: "%netgen_block_manager.core.service.layout_resolver.mapper.class%"
        arguments:
            - "@netgen_block_manager.persistence.handler"

    netgen_block_manager.core.service.layout_resolver:
        class: "%netgen_block_manager.core.service.layout_resolver.class%"
        arguments:
            - "@netgen_block_manager.core.service.layout_resolver.validator"
            - "@netgen_block_manager.core.service.layout_resolver.mapper"
            - "@netgen_block_manager.persistence.handler"

    # Service aliases

    netgen_block_manager.api.repository:
        alias: netgen_block_manager.core.repository

    netgen_block_manager.api.service.layout:
        alias: netgen_block_manager.core.service.layout

    netgen_block_manager.api.service.block:
        alias: netgen_block_manager.core.service.block

    netgen_block_manager.api.service.collection:
        alias: netgen_block_manager.core.service.collection

    netgen_block_manager.api.service.layout_resolver:
        alias: netgen_block_manager.core.service.layout_resolver

    netgen_block_manager.persistence.handler:
        alias: netgen_block_manager.persistence.doctrine.handler
