parameters:
    netgen_block_manager.block.form.full_edit.class: Netgen\BlockManager\Block\Form\FullEditType

services:
    netgen_block_manager.block.form.full_edit:
        class: "%netgen_block_manager.block.form.full_edit.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
        tags:
            - { name: form.type, alias: block_full_edit }
