parameters:
    netgen_block_manager.block.form.edit.class: Netgen\BlockManager\Block\Form\EditType
    netgen_block_manager.block.form.full_edit.class: Netgen\BlockManager\Block\Form\FullEditType
    netgen_block_manager.block.form.design_edit.class: Netgen\BlockManager\Block\Form\DesignEditType
    netgen_block_manager.block.form.content_edit.class: Netgen\BlockManager\Block\Form\ContentEditType

services:
    netgen_block_manager.block.form.edit:
        class: "%netgen_block_manager.block.form.edit.class%"
        abstract: true

    netgen_block_manager.block.form.full_edit:
        class: "%netgen_block_manager.block.form.full_edit.class%"
        parent: netgen_block_manager.block.form.edit
        tags:
            - { name: form.type }

    netgen_block_manager.block.form.design_edit:
        class: "%netgen_block_manager.block.form.design_edit.class%"
        parent: netgen_block_manager.block.form.edit
        tags:
            - { name: form.type }

    netgen_block_manager.block.form.content_edit:
        class: "%netgen_block_manager.block.form.content_edit.class%"
        parent: netgen_block_manager.block.form.edit
        tags:
            - { name: form.type }
