parameters:
    netgen_block_manager.block.form.edit.class: Netgen\BlockManager\Block\Form\EditType
    netgen_block_manager.block.form.inline.class: Netgen\BlockManager\Block\Form\InlineType
    netgen_block_manager.block.form.inline.title.class: Netgen\BlockManager\Block\Form\InlineType\TitleType
    netgen_block_manager.block.form.inline.paragraph.class: Netgen\BlockManager\Block\Form\InlineType\ParagraphType

services:
    netgen_block_manager.block.form.edit:
        class: "%netgen_block_manager.block.form.edit.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
        tags:
            - { name: form.type, alias: block_edit }
