parameters:
    netgen_block_manager.block.block_definition.class: Netgen\BlockManager\Block\BlockDefinition
    netgen_block_manager.block.block_definition.configuration.class: Netgen\BlockManager\Block\BlockDefinition\Configuration\Configuration
    netgen_block_manager.block.block_definition.configuration.factory.class: Netgen\BlockManager\Block\BlockDefinition\Configuration\Factory
    netgen_block_manager.block.registry.block_definition.class: Netgen\BlockManager\Block\Registry\BlockDefinitionRegistry

    netgen_block_manager.block.block_definition.handler.title.class: Netgen\BlockManager\Block\BlockDefinition\Handler\TitleHandler
    netgen_block_manager.block.block_definition.handler.paragraph.class: Netgen\BlockManager\Block\BlockDefinition\Handler\ParagraphHandler
    netgen_block_manager.block.block_definition.handler.rich_text.class: Netgen\BlockManager\Block\BlockDefinition\Handler\RichTextHandler
    netgen_block_manager.block.block_definition.handler.external_video.class: Netgen\BlockManager\Block\BlockDefinition\Handler\ExternalVideoHandler
    netgen_block_manager.block.block_definition.handler.html_snippet.class: Netgen\BlockManager\Block\BlockDefinition\Handler\HtmlSnippetHandler
    netgen_block_manager.block.block_definition.handler.twig_block.class: Netgen\BlockManager\Block\BlockDefinition\Handler\TwigBlockHandler
    netgen_block_manager.block.block_definition.handler.map.class: Netgen\BlockManager\Block\BlockDefinition\Handler\MapHandler
    netgen_block_manager.block.block_definition.handler.list.class: Netgen\BlockManager\Block\BlockDefinition\Handler\ListHandler
    netgen_block_manager.block.block_definition.handler.gallery.class: Netgen\BlockManager\Block\BlockDefinition\Handler\GalleryHandler

    netgen_block_manager.block.block_definition.handler.title.options:
        h1: 'Heading 1'
        h2: 'Heading 2'
        h3: 'Heading 3'

    netgen_block_manager.block.block_definition.handler.external_video.services:
        youtube: 'YouTube'
        vimeo: 'Vimeo'

    netgen_block_manager.block.block_definition.handler.map.min_zoom: 0
    netgen_block_manager.block.block_definition.handler.map.max_zoom: 20
    netgen_block_manager.block.block_definition.handler.map.map_types:
        roadmap: 'Roadmap'
        satellite: 'Satellite'
        hybrid: 'Hybrid'
        terrain: 'Terrain'

    netgen_block_manager.block.block_definition.handler.list.columns:
        1: '1 column'
        2: '2 columns'
        3: '3 columns'
        4: '4 columns'
        6: '6 columns'

    netgen_block_manager.block.block_definition.handler.gallery.pagination_types:
        horizontal: 'Horizontal'
        vertical: 'Vertical'
        fraction: 'Fraction'

    netgen_block_manager.block.block_definition.handler.gallery.min_autoplay_time: 1
    netgen_block_manager.block.block_definition.handler.gallery.max_autoplay_time: 12

    netgen_block_manager.block.block_definition.handler.gallery.transitions:
        default: 'Default'
        fade: 'Fade'

    netgen_block_manager.block.block_definition.handler.gallery.aspect_ratios:
        16_9: '16:9'
        3_2: '3:2'
        4_3: '4:3'
        1_1: '1:1'

services:
    netgen_block_manager.block.registry.block_definition:
        class: "%netgen_block_manager.block.registry.block_definition.class%"

    netgen_block_manager.block.block_definition.handler.title:
        class: "%netgen_block_manager.block.block_definition.handler.title.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.title.options%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'title' }

    netgen_block_manager.block.block_definition.handler.paragraph:
        class: "%netgen_block_manager.block.block_definition.handler.paragraph.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'paragraph' }

    netgen_block_manager.block.block_definition.handler.rich_text:
        class: "%netgen_block_manager.block.block_definition.handler.rich_text.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'rich_text' }

    netgen_block_manager.block.block_definition.handler.external_video:
        class: "%netgen_block_manager.block.block_definition.handler.external_video.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.external_video.services%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'external_video' }

    netgen_block_manager.block.block_definition.handler.html_snippet:
        class: "%netgen_block_manager.block.block_definition.handler.html_snippet.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'html_snippet' }

    netgen_block_manager.block.block_definition.handler.twig_block:
        class: "%netgen_block_manager.block.block_definition.handler.twig_block.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'twig_block' }

    netgen_block_manager.block.block_definition.handler.map:
        class: "%netgen_block_manager.block.block_definition.handler.map.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.map.min_zoom%"
            - "%netgen_block_manager.block.block_definition.handler.map.max_zoom%"
            - "%netgen_block_manager.block.block_definition.handler.map.map_types%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'map' }

    netgen_block_manager.block.block_definition.handler.list:
        class: "%netgen_block_manager.block.block_definition.handler.list.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.list.columns%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'list' }

    netgen_block_manager.block.block_definition.handler.gallery:
        class: "%netgen_block_manager.block.block_definition.handler.gallery.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.gallery.min_autoplay_time%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.max_autoplay_time%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.pagination_types%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.transitions%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.aspect_ratios%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'gallery' }
