services:
    netgen_block_manager.block.block_definition_factory:
        class: Netgen\BlockManager\Block\BlockDefinitionFactory
        public: false
        arguments:
            - "@netgen_block_manager.parameters.translatable_parameter_builder_factory"
            - "@netgen_block_manager.block.registry.handler_plugin"

    netgen_block_manager.block.registry.block_definition:
        class: Netgen\BlockManager\Block\Registry\BlockDefinitionRegistry
        public: true

    netgen_block_manager.block.registry.handler_plugin:
        class: Netgen\BlockManager\Block\Registry\HandlerPluginRegistry
        public: false

    netgen_block_manager.block.registry.block_type:
        class: Netgen\BlockManager\Block\Registry\BlockTypeRegistry
        public: true

    netgen_block_manager.block.registry.block_type_group:
        class: Netgen\BlockManager\Block\Registry\BlockTypeGroupRegistry
        public: true
