parameters:
    netgen_block_manager.block.block_definition.handler.title.tags:
        h1: 'Heading 1'
        h2: 'Heading 2'
        h3: 'Heading 3'

    netgen_block_manager.block.block_definition.handler.title.value_types: []

    netgen_block_manager.block.block_definition.handler.button.styles:
        'default_button': 'Default button'
        'highlighted_button': 'Highlighted button'
        'link': 'Link'

    netgen_block_manager.block.block_definition.handler.button.value_types: []

    netgen_block_manager.block.block_definition.handler.external_video.services:
        youtube: 'YouTube'
        vimeo: 'Vimeo'

    netgen_block_manager.block.block_definition.handler.full_view.twig_block_name: content

    netgen_block_manager.block.block_definition.handler.map.min_zoom: 0
    netgen_block_manager.block.block_definition.handler.map.max_zoom: 20
    netgen_block_manager.block.block_definition.handler.map.map_types:
        ROADMAP: 'Roadmap'
        SATELLITE: 'Satellite'
        HYBRID: 'Hybrid'
        TERRAIN: 'Terrain'

    netgen_block_manager.block.block_definition.handler.list.columns:
        2: '2 columns'
        3: '3 columns'
        4: '4 columns'
        6: '6 columns'

    netgen_block_manager.block.block_definition.handler.gallery.pagination_types:
        horizontal: 'Horizontal'
        vertical: 'Vertical'
        fraction: 'Fraction'

    netgen_block_manager.block.block_definition.handler.gallery.min_autoplay_time: 1
    netgen_block_manager.block.block_definition.handler.gallery.max_autoplay_time: 12

    netgen_block_manager.block.block_definition.handler.gallery.transitions:
        slide: 'Slide'
        fade: 'Fade'

    netgen_block_manager.block.block_definition.handler.gallery.aspect_ratios:
        16_9: '16:9'
        3_2: '3:2'
        4_3: '4:3'
        1_1: '1:1'

services:
    netgen_block_manager.block.block_definition_factory:
        class: Netgen\BlockManager\Block\BlockDefinitionFactory
        arguments:
            - "@netgen_block_manager.parameters.parameter_builder_factory"
            - "@netgen_block_manager.config.registry.config_definition"

    netgen_block_manager.block.registry.block_definition:
        class: Netgen\BlockManager\Block\Registry\BlockDefinitionRegistry

    netgen_block_manager.block.registry.block_type:
        class: Netgen\BlockManager\Block\Registry\BlockTypeRegistry

    netgen_block_manager.block.registry.block_type_group:
        class: Netgen\BlockManager\Block\Registry\BlockTypeGroupRegistry

    netgen_block_manager.block.block_definition.handler.title:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\TitleHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.title.tags%"
            - "%netgen_block_manager.block.block_definition.handler.title.value_types%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: title }

    netgen_block_manager.block.block_definition.handler.text:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\TextHandler
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: text }

    netgen_block_manager.block.block_definition.handler.button:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\ButtonHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.button.styles%"
            - "%netgen_block_manager.block.block_definition.handler.button.value_types%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: button }

    netgen_block_manager.block.block_definition.handler.markdown.parser:
        class: Michelf\MarkdownExtra

    netgen_block_manager.block.block_definition.handler.markdown:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\MarkdownHandler
        arguments:
            - "@netgen_block_manager.block.block_definition.handler.markdown.parser"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: markdown }

    netgen_block_manager.block.block_definition.handler.rich_text:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\RichTextHandler
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: rich_text }

    netgen_block_manager.block.block_definition.handler.external_video:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\ExternalVideoHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.external_video.services%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: external_video }

    netgen_block_manager.block.block_definition.handler.html_snippet:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\HtmlSnippetHandler
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: html_snippet }

    netgen_block_manager.block.block_definition.handler.full_view:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\Twig\FullViewHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.full_view.twig_block_name%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: full_view }

    netgen_block_manager.block.block_definition.handler.twig_block:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\Twig\TwigBlockHandler
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: twig_block }

    netgen_block_manager.block.block_definition.handler.map:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\MapHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.map.min_zoom%"
            - "%netgen_block_manager.block.block_definition.handler.map.max_zoom%"
            - "%netgen_block_manager.block.block_definition.handler.map.map_types%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: map }

    netgen_block_manager.block.block_definition.handler.list:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\ListHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.list.columns%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: list }

    netgen_block_manager.block.block_definition.handler.gallery:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\GalleryHandler
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.gallery.min_autoplay_time%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.max_autoplay_time%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.pagination_types%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.transitions%"
            - "%netgen_block_manager.block.block_definition.handler.gallery.aspect_ratios%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: gallery }

    netgen_block_manager.block.block_definition.handler.column:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\Container\ColumnHandler
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: column }

    netgen_block_manager.block.block_definition.handler.two_columns:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\Container\TwoColumnsHandler
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: two_columns }
