parameters:
    netgen_block_manager.block.block_definition.class: Netgen\BlockManager\Block\BlockDefinition
    netgen_block_manager.block.block_definition.configuration.class: Netgen\BlockManager\Block\BlockDefinition\Configuration\Configuration
    netgen_block_manager.block.block_definition.configuration.factory.class: Netgen\BlockManager\Block\BlockDefinition\Configuration\Factory
    netgen_block_manager.block.registry.block_definition.class: Netgen\BlockManager\Block\Registry\BlockDefinitionRegistry

    netgen_block_manager.block.block_definition.handler.title.class: Netgen\BlockManager\Block\BlockDefinition\Handler\TitleHandler
    netgen_block_manager.block.block_definition.handler.paragraph.class: Netgen\BlockManager\Block\BlockDefinition\Handler\ParagraphHandler
    netgen_block_manager.block.block_definition.handler.html_snippet.class: Netgen\BlockManager\Block\BlockDefinition\Handler\HtmlSnippetHandler
    netgen_block_manager.block.block_definition.handler.twig_block.class: Netgen\BlockManager\Block\BlockDefinition\Handler\TwigBlockHandler
    netgen_block_manager.block.block_definition.handler.map.class: Netgen\BlockManager\Block\BlockDefinition\Handler\MapHandler

    netgen_block_manager.block.block_definition.handler.title.options:
        h1: 'Heading 1'
        h2: 'Heading 2'
        h3: 'Heading 3'

    netgen_block_manager.block.block_definition.handler.map.min_zoom: 0
    netgen_block_manager.block.block_definition.handler.map.max_zoom: 20
    netgen_block_manager.block.block_definition.handler.map.map_types:
        roadmap: 'Roadmap'
        satellite: 'Satellite'
        hybrid: 'Hybrid'
        terrain: 'Terrain'

services:
    netgen_block_manager.block.registry.block_definition:
        class: "%netgen_block_manager.block.registry.block_definition.class%"

    netgen_block_manager.block.block_definition.handler.title:
        class: "%netgen_block_manager.block.block_definition.handler.title.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.title.options%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'title' }

    netgen_block_manager.block.block_definition.handler.paragraph:
        class: "%netgen_block_manager.block.block_definition.handler.paragraph.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'paragraph' }

    netgen_block_manager.block.block_definition.handler.html_snippet:
        class: "%netgen_block_manager.block.block_definition.handler.html_snippet.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'html_snippet' }

    netgen_block_manager.block.block_definition.handler.twig_block:
        class: "%netgen_block_manager.block.block_definition.handler.twig_block.class%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'twig_block' }

    netgen_block_manager.block.block_definition.handler.map:
        class: "%netgen_block_manager.block.block_definition.handler.map.class%"
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.map.min_zoom%"
            - "%netgen_block_manager.block.block_definition.handler.map.max_zoom%"
            - "%netgen_block_manager.block.block_definition.handler.map.map_types%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: 'map' }
