services:
    netgen_block_manager.collection.result_iterator_factory:
        class: Netgen\BlockManager\Collection\Result\ResultIteratorFactory
        arguments:
            - "@netgen_block_manager.item.item_loader"
            - "@netgen_block_manager.item.item_builder"

    netgen_block_manager.collection.collection_iterator_factory:
        class: Netgen\BlockManager\Collection\Result\CollectionIteratorFactory
        arguments:
            - "%netgen_block_manager.collection.contextual_query_limit%"

    netgen_block_manager.collection.result_loader:
        class: Netgen\BlockManager\Collection\Result\ResultLoader
        arguments:
            - "@netgen_block_manager.collection.result_iterator_factory"
            - "@netgen_block_manager.collection.collection_iterator_factory"

    netgen_block_manager.collection.query_type_factory:
        class: Netgen\BlockManager\Collection\QueryTypeFactory
        arguments:
            - "@netgen_block_manager.parameters.parameter_builder_factory"

    netgen_block_manager.collection.registry.query_type:
        class: Netgen\BlockManager\Collection\Registry\QueryTypeRegistry

    netgen_block_manager.collection.registry.source:
        class: Netgen\BlockManager\Collection\Registry\SourceRegistry
