services:
    netgen_block_manager.collection.result_iterator_factory:
        class: Netgen\BlockManager\Collection\Result\ResultIteratorFactory
        public: false
        arguments:
            - "@netgen_block_manager.item.item_loader"
            - "@netgen_block_manager.item.item_builder"

    netgen_block_manager.collection.collection_iterator_factory:
        class: Netgen\BlockManager\Collection\Result\CollectionIteratorFactory
        public: false
        arguments:
            - "%netgen_block_manager.collection.contextual_query_limit%"

    netgen_block_manager.collection.result_builder:
        class: Netgen\BlockManager\Collection\Result\ResultBuilder
        arguments:
            - "@netgen_block_manager.collection.result_iterator_factory"
            - "@netgen_block_manager.collection.collection_iterator_factory"
            - "%netgen_block_manager.collection.max_limit%"

    netgen_block_manager.collection.result.pagerfanta.factory:
        class: Netgen\BlockManager\Collection\Result\Pagerfanta\PagerFactory
        arguments:
            - "@netgen_block_manager.collection.result_builder"
            - "%netgen_block_manager.collection.max_limit%"

    netgen_block_manager.collection.query_type_factory:
        class: Netgen\BlockManager\Collection\QueryTypeFactory
        public: false
        arguments:
            - "@netgen_block_manager.parameters.translatable_parameter_builder_factory"

    netgen_block_manager.collection.registry.query_type:
        class: Netgen\BlockManager\Collection\Registry\QueryTypeRegistry
