services:
    netgen_block_manager.config.config_definition_factory:
        class: Netgen\BlockManager\Config\ConfigDefinitionFactory
        public: false
        arguments:
            - "@netgen_block_manager.parameters.parameter_builder_factory"

    netgen_block_manager.block.config_definition.handler.http_cache:
        class: Netgen\BlockManager\Block\ConfigDefinition\Handler\HttpCacheConfigHandler
        public: false
        arguments:
            - "@netgen_block_manager.http_cache.block.cacheable_resolver"
        tags:
            - { name: netgen_block_manager.block.config_definition_handler, config_key: http_cache }
