services:
    netgen_block_manager.config.config_definition_factory:
        class: Netgen\BlockManager\Config\ConfigDefinitionFactory
        arguments:
            - "@netgen_block_manager.parameters.parameter_builder_factory"

    netgen_block_manager.config.config_definition.handler.block.http_cache:
        class: Netgen\BlockManager\Config\ConfigDefinition\Block\HttpCacheConfigHandler
        arguments:
            - "@netgen_block_manager.http_cache.block.cacheable_resolver"
        tags:
            - { name: netgen_block_manager.config.config_definition_handler, type: block, identifier: http_cache }
