services:
    netgen_block_manager.configuration.container:
        class: Netgen\BlockManager\Configuration\ContainerConfiguration
        calls:
            - [setContainer, ["@service_container"]]

    netgen_block_manager.configuration:
        alias: netgen_block_manager.configuration.container

    # Registries

    netgen_block_manager.configuration.registry.source:
        class: Netgen\BlockManager\Configuration\Registry\SourceRegistry

    netgen_block_manager.configuration.registry.layout_type:
        class: Netgen\BlockManager\Configuration\Registry\LayoutTypeRegistry

    netgen_block_manager.configuration.registry.container_type:
        class: Netgen\BlockManager\Configuration\Registry\ContainerTypeRegistry

    netgen_block_manager.configuration.registry.block_type:
        class: Netgen\BlockManager\Configuration\Registry\BlockTypeRegistry

    # Synthetic services

    netgen_block_manager.configuration.source:
        class: Netgen\BlockManager\Configuration\Source\Source
        factory: [Netgen\BlockManager\Configuration\Factory\SourceFactory, buildSource]
        abstract: true
        synthetic: true

    netgen_block_manager.configuration.layout_type:
        class: Netgen\BlockManager\Configuration\LayoutType\LayoutType
        factory: [Netgen\BlockManager\Configuration\Factory\LayoutTypeFactory, buildLayoutType]
        abstract: true
        synthetic: true

    netgen_block_manager.configuration.container_type:
        class: Netgen\BlockManager\Configuration\ContainerType\ContainerType
        factory: [Netgen\BlockManager\Configuration\Factory\ContainerTypeFactory, buildContainerType]
        abstract: true
        synthetic: true

    netgen_block_manager.configuration.block_type:
        class: Netgen\BlockManager\Configuration\BlockType\BlockType
        factory: [Netgen\BlockManager\Configuration\Factory\BlockTypeFactory, buildBlockType]
        abstract: true
        synthetic: true

    netgen_block_manager.configuration.block_type_group:
        class: Netgen\BlockManager\Configuration\BlockType\BlockTypeGroup
        factory: [Netgen\BlockManager\Configuration\Factory\BlockTypeGroupFactory, buildBlockTypeGroup]
        abstract: true
        synthetic: true
