parameters:
    netgen_block_manager.configuration.container.class: Netgen\BlockManager\Configuration\ContainerConfiguration

services:
    netgen_block_manager.configuration.container:
        class: "%netgen_block_manager.configuration.container.class%"
        arguments:
            - [setContainer, ["@service_container"]]

    netgen_block_manager.configuration:
        alias: netgen_block_manager.configuration.container
