services:
    netgen_block_manager.config.config_definition_factory:
        class: Netgen\BlockManager\Config\ConfigDefinitionFactory
        public: false
        arguments:
            - "@netgen_block_manager.parameters.parameter_builder_factory"

    netgen_block_manager.collection.item.config_definition.handler.visibility:
        class: Netgen\BlockManager\Collection\Item\ConfigDefinition\Handler\VisibilityConfigHandler
        public: false
        tags:
            - { name: netgen_block_manager.collection.item_config_handler, config_key: visibility }
