services:
    netgen_block_manager.configuration.container:
        class: Netgen\BlockManager\Configuration\ContainerConfiguration
        calls:
            - [setContainer, ["@service_container"]]

    netgen_block_manager.configuration:
        alias: netgen_block_manager.configuration.container

    # Registries

    netgen_block_manager.configuration.registry.source:
        class: Netgen\BlockManager\Configuration\Registry\SourceRegistry
