services:
    netgen_block_manager.container.registry.container_definition:
        class: Netgen\BlockManager\Layout\Container\Registry\ContainerDefinitionRegistry

    netgen_block_manager.container.container_definition.handler.dynamic:
        class: Netgen\BlockManager\Layout\Container\ContainerDefinition\Handler\DynamicContainerHandler
        tags:
            - { name: netgen_block_manager.container.container_definition_handler, identifier: dynamic }

    netgen_block_manager.container.container_definition.handler.two_columns:
        class: Netgen\BlockManager\Layout\Container\ContainerDefinition\Handler\TwoColumnsContainerHandler
        tags:
            - { name: netgen_block_manager.container.container_definition_handler, identifier: two_columns }
