parameters:
    netgen_block_manager.controller.base.class: Netgen\Bundle\BlockManagerBundle\Controller\Controller

    netgen_block_manager.controller.block.class: Netgen\Bundle\BlockManagerBundle\Controller\BlockController
    netgen_block_manager.controller.layout.class: Netgen\Bundle\BlockManagerBundle\Controller\LayoutController

    netgen_block_manager.controller.api.v1.config.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\ConfigController
    netgen_block_manager.controller.api.v1.layout.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\LayoutController
    netgen_block_manager.controller.api.v1.block.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\BlockController
    netgen_block_manager.controller.api.v1.block_collection.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\BlockCollectionController

    netgen_block_manager.controller.api.v1.block.validator.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\BlockValidator
    netgen_block_manager.controller.api.v1.collection.validator.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\CollectionValidator

    netgen_block_manager.controller.block_manager.index.class: Netgen\Bundle\BlockManagerBundle\Controller\BlockManager\IndexController

services:
    netgen_block_manager.controller.base:
        class: "%netgen_block_manager.controller.base.class%"
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]

    netgen_block_manager.controller.block:
        class: "%netgen_block_manager.controller.block.class%"
        parent: netgen_block_manager.controller.base

    ngbm_block:
        alias: netgen_block_manager.controller.block

    netgen_block_manager.controller.layout:
        class: "%netgen_block_manager.controller.layout.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    ngbm_layout:
        alias: netgen_block_manager.controller.layout

    # API controllers

    netgen_block_manager.controller.api.v1.config:
        class: "%netgen_block_manager.controller.api.v1.config.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.configuration.registry.block_type"
            - "@netgen_block_manager.configuration.registry.source"

    netgen_block_manager.controller.api.v1.layout:
        class: "%netgen_block_manager.controller.api.v1.layout.class%"
        parent: netgen_block_manager.controller.base

    netgen_block_manager.controller.api.v1.block:
        class: "%netgen_block_manager.controller.api.v1.block.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.controller.api.v1.block.validator"

    netgen_block_manager.controller.api.v1.block_collection:
        class: "%netgen_block_manager.controller.api.v1.block_collection.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.collection"
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.controller.api.v1.collection.validator"

    netgen_block_manager.controller.api.v1.block.validator:
        class: "%netgen_block_manager.controller.api.v1.block.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.controller.api.v1.collection.validator:
        class: "%netgen_block_manager.controller.api.v1.collection.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    # Block Manager app controllers

    netgen_block_manager.controller.block_manager.index:
        class: "%netgen_block_manager.controller.block_manager.index.class%"
        parent: netgen_block_manager.controller.base
