services:
    netgen_block_manager.controller.base:
        class: Netgen\Bundle\BlockManagerBundle\Controller\Controller
        abstract: true
        calls:
            - [initialize, ["@service_container"]]

    netgen_block_manager.controller.validator:
        class: Netgen\Bundle\BlockManagerBundle\Controller\Validator\Validator
        public: false
        abstract: true
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.controller.block:
        class: Netgen\Bundle\BlockManagerBundle\Controller\BlockController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: monolog.logger, channel: ngbm }

    ngbm_block:
        alias: netgen_block_manager.controller.block

    # API controllers

    netgen_block_manager.controller.api.v1.config:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\ConfigController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.block.registry.block_type"
            - "@netgen_block_manager.block.registry.block_type_group"
            - "@netgen_block_manager.layout.registry.layout_type"
            - "@security.csrf.token_manager"
            - "%netgen_block_manager.api.csrf_token_id%"

    netgen_block_manager.controller.api.v1.layout:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\LayoutController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.controller.api.v1.layout.validator"

    netgen_block_manager.controller.api.v1.block:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\BlockController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.controller.api.v1.block.validator"

    netgen_block_manager.controller.api.v1.block_collection:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\BlockCollectionController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.collection"
            - "@netgen_block_manager.controller.api.v1.block_collection.validator"
            - "@netgen_block_manager.collection.result_builder"

    netgen_block_manager.controller.api.v1.collection:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\CollectionController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.collection"

    netgen_block_manager.controller.api.v1.block.validator:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\BlockValidator
        public: false
        parent: netgen_block_manager.controller.validator

    netgen_block_manager.controller.api.v1.block_collection.validator:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\BlockCollectionValidator
        public: false
        parent: netgen_block_manager.controller.validator

    netgen_block_manager.controller.api.v1.layout.validator:
        class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\LayoutValidator
        public: false
        parent: netgen_block_manager.controller.validator
