parameters:
    netgen_block_manager.controller.base.class: Netgen\Bundle\BlockManagerBundle\Controller\Controller

    netgen_block_manager.controller.block.class: Netgen\Bundle\BlockManagerBundle\Controller\BlockController

    netgen_block_manager.controller.api.v1.config.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\ConfigController
    netgen_block_manager.controller.api.v1.layout.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\LayoutController
    netgen_block_manager.controller.api.v1.block.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\BlockController
    netgen_block_manager.controller.api.v1.block_collection.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\BlockCollectionController
    netgen_block_manager.controller.api.v1.collection.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\CollectionController
    netgen_block_manager.controller.api.v1.layout_resolver.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\LayoutResolverController

    netgen_block_manager.controller.api.v1.block.validator.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\BlockValidator
    netgen_block_manager.controller.api.v1.layout.validator.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\LayoutValidator
    netgen_block_manager.controller.api.v1.collection.validator.class: Netgen\Bundle\BlockManagerBundle\Controller\API\V1\Validator\CollectionValidator

services:
    netgen_block_manager.controller.base:
        class: "%netgen_block_manager.controller.base.class%"
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]

    netgen_block_manager.controller.block:
        class: "%netgen_block_manager.controller.block.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: monolog.logger, channel: ngbm }

    ngbm_block:
        alias: netgen_block_manager.controller.block

    # API controllers

    netgen_block_manager.controller.api.v1.config:
        class: "%netgen_block_manager.controller.api.v1.config.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.configuration.registry.block_type"
            - "@netgen_block_manager.configuration.registry.layout_type"
            - "@netgen_block_manager.configuration.registry.source"
            - "@?security.csrf.token_manager"
            - "%netgen_block_manager.api.csrf_token_id%"

    netgen_block_manager.controller.api.v1.layout:
        class: "%netgen_block_manager.controller.api.v1.layout.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.repository"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.controller.api.v1.layout.validator"

    netgen_block_manager.controller.api.v1.block:
        class: "%netgen_block_manager.controller.api.v1.block.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.controller.api.v1.block.validator"

    netgen_block_manager.controller.api.v1.block_collection:
        class: "%netgen_block_manager.controller.api.v1.block_collection.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.collection"
            - "@netgen_block_manager.collection.result_generator"

    netgen_block_manager.controller.api.v1.collection:
        class: "%netgen_block_manager.controller.api.v1.collection.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.repository"
            - "@netgen_block_manager.collection.result_generator"
            - "@netgen_block_manager.controller.api.v1.collection.validator"

    netgen_block_manager.controller.api.v1.layout_resolver:
        class: "%netgen_block_manager.controller.api.v1.layout_resolver.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.api.v1.block.validator:
        class: "%netgen_block_manager.controller.api.v1.block.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.controller.api.v1.layout.validator:
        class: "%netgen_block_manager.controller.api.v1.layout.validator.class%"
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.controller.api.v1.collection.validator:
        class: "%netgen_block_manager.controller.api.v1.collection.validator.class%"
        calls:
            - [setValidator, ["@validator"]]
