services:
    netgen_block_manager.event_listener.exception_conversion:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionConversionListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.exception_serializer:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionSerializerListener
        # public: false
        arguments:
            - "@serializer"
            - "@?logger"
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.event_listener.serializer:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\SerializerListener
        # public: false
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.request_body_listener:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\RequestBodyListener
        # public: false
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.view:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ViewListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.view_renderer:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ViewRendererListener
        # public: false
        arguments:
            - "@netgen_block_manager.view.view_renderer"
            - "@netgen_block_manager.error.handler"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.set_is_api_request:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\SetIsApiRequestListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.twig_extensions:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\TwigExtensionsListener
        # public: false
        arguments:
            - "@twig"
        # Set as lazy to prevent crashing of eZ Platform siteaccess aware config
        lazy: true
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.api_csrf_validation_listener:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\CsrfValidation\ApiCsrfValidationListener
        # public: false
        arguments:
            - "@security.csrf.token_manager"
            - "%netgen_block_manager.api.csrf_token_id%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_collection_results:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetCollectionResultsListener
        # public: false
        arguments:
            - "@netgen_block_manager.collection.result.pagerfanta.factory"
            - "%netgen_block_manager.block_view.collection_results_contexts%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_collection_pager:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetCollectionPagerListener
        # public: false
        arguments:
            - "@netgen_block_manager.collection.result.pagerfanta.factory"
            - "@request_stack"
            - "%netgen_block_manager.block_view.collection_pager_contexts%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_twig_block_content:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetTwigBlockContentListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.invalidation:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\InvalidationListener
        # public: false
        arguments:
            - "@netgen_block_manager.http_cache.client"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.cacheable_view:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\CacheableViewListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.layout_response:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\LayoutResponseListener
        # public: false
        arguments:
            - "@netgen_block_manager.http_cache.tagger"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.block_response:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\BlockResponseListener
        # public: false
        arguments:
            - "@netgen_block_manager.http_cache.tagger"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.context:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ContextListener
        # public: false
        arguments:
            - "@netgen_block_manager.context"
            - "@netgen_block_manager.context.builder"
            - "@uri_signer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.ajax_block_request:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\AjaxBlockRequestListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }
