parameters:
    netgen_block_manager.event_listener.exception_conversion.class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionConversionListener
    netgen_block_manager.event_listener.exception_serializer.class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionSerializerListener
    netgen_block_manager.event_listener.serializer.class: Netgen\Bundle\BlockManagerBundle\EventListener\SerializerListener
    netgen_block_manager.event_listener.request_body_listener.class: Netgen\Bundle\BlockManagerBundle\EventListener\RequestBodyListener
    netgen_block_manager.event_listener.view_renderer.class: Netgen\Bundle\BlockManagerBundle\EventListener\ViewRendererListener
    netgen_block_manager.event_listener.set_is_api_request.class: Netgen\Bundle\BlockManagerBundle\EventListener\SetIsApiRequestListener
    netgen_block_manager.event_listener.layout_resolver.class: Netgen\Bundle\BlockManagerBundle\EventListener\LayoutResolverListener

    netgen_block_manager.event_listener.block_collection.class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockCollectionListener
    netgen_block_manager.event_listener.collection_item.class: Netgen\Bundle\BlockManagerBundle\EventListener\CollectionItemListener
    netgen_block_manager.event_listener.collection_query.class: Netgen\Bundle\BlockManagerBundle\EventListener\CollectionQueryListener

services:
    netgen_block_manager.event_listener.exception_conversion:
        class: "%netgen_block_manager.event_listener.exception_conversion.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.exception_serializer:
        class: "%netgen_block_manager.event_listener.exception_serializer.class%"
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.serializer:
        class: "%netgen_block_manager.event_listener.serializer.class%"
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.request_body_listener:
        class: "%netgen_block_manager.event_listener.request_body_listener.class%"
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.view_renderer:
        class: "%netgen_block_manager.event_listener.view_renderer.class%"
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.set_is_api_request:
        class: "%netgen_block_manager.event_listener.set_is_api_request.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.layout_resolver:
        class: "%netgen_block_manager.event_listener.layout_resolver.class%"
        arguments:
            - "@netgen_block_manager.layout_resolver"
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.view.builder"
            - "@netgen_block_manager.templating.global_helper"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_collection:
        class: "%netgen_block_manager.event_listener.block_collection.class%"
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.collection_item:
        class: "%netgen_block_manager.event_listener.collection_item.class%"
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.collection_query:
        class: "%netgen_block_manager.event_listener.collection_query.class%"
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: kernel.event_subscriber }
