parameters:
    netgen_block_manager.event_listener.exception_conversion.class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionConversionListener
    netgen_block_manager.event_listener.exception_serializer.class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionSerializerListener
    netgen_block_manager.event_listener.serializer.class: Netgen\Bundle\BlockManagerBundle\EventListener\SerializerListener
    netgen_block_manager.event_listener.request_body_listener.class: Netgen\Bundle\BlockManagerBundle\EventListener\RequestBodyListener
    netgen_block_manager.event_listener.view_renderer.class: Netgen\Bundle\BlockManagerBundle\EventListener\ViewRendererListener
    netgen_block_manager.event_listener.set_is_api_request.class: Netgen\Bundle\BlockManagerBundle\EventListener\SetIsApiRequestListener
    netgen_block_manager.event_listener.pagelayout.class: Netgen\Bundle\BlockManagerBundle\EventListener\PageLayoutListener
    netgen_block_manager.event_listener.layout_resolver.class: Netgen\Bundle\BlockManagerBundle\EventListener\LayoutResolverListener
    netgen_block_manager.event_listener.api_csrf_validation_listener.class: Netgen\Bundle\BlockManagerBundle\EventListener\ApiCsrfValidationListener

    netgen_block_manager.event_listener.block_view.get_collection_results.class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetCollectionResultsListener
    netgen_block_manager.event_listener.block_view.get_dynamic_parameters.class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetDynamicParametersListener

services:
    netgen_block_manager.event_listener.exception_conversion:
        class: "%netgen_block_manager.event_listener.exception_conversion.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.exception_serializer:
        class: "%netgen_block_manager.event_listener.exception_serializer.class%"
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.serializer:
        class: "%netgen_block_manager.event_listener.serializer.class%"
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.request_body_listener:
        class: "%netgen_block_manager.event_listener.request_body_listener.class%"
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.view_renderer:
        class: "%netgen_block_manager.event_listener.view_renderer.class%"
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.set_is_api_request:
        class: "%netgen_block_manager.event_listener.set_is_api_request.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.pagelayout:
        class: "%netgen_block_manager.event_listener.pagelayout.class%"
        arguments:
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.templating.global_helper"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.layout_resolver:
        class: "%netgen_block_manager.event_listener.layout_resolver.class%"
        arguments:
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.view.builder"
            - "@netgen_block_manager.templating.global_helper"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.api_csrf_validation_listener:
        class: "%netgen_block_manager.event_listener.api_csrf_validation_listener.class%"
        arguments:
            - "@security.csrf.token_manager"
            - "%netgen_block_manager.api.csrf_token_id%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_collection_results:
        class: "%netgen_block_manager.event_listener.block_view.get_collection_results.class%"
        arguments:
            - "@netgen_block_manager.collection.result_generator"
            - "@netgen_block_manager.api.service.block"
            - "%netgen_block_manager.block_view.collection_results_contexts%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_dynamic_parameters:
        class: "%netgen_block_manager.event_listener.block_view.get_dynamic_parameters.class%"
        arguments:
            - "%netgen_block_manager.block_view.dynamic_parameters_contexts%"
        tags:
            - { name: kernel.event_subscriber }
