services:
    netgen_block_manager.event_listener.exception_conversion:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionConversionListener
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.exception_serializer:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionSerializerListener
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.serializer:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\SerializerListener
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.request_body_listener:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\RequestBodyListener
        arguments:
            - "@serializer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.view_renderer:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\ViewRendererListener
        arguments:
            - "@netgen_block_manager.view.view_renderer"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.set_is_api_request:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\SetIsApiRequestListener
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.api_csrf_validation_listener:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\CsrfValidation\ApiCsrfValidationListener
        arguments:
            - "@security.csrf.token_manager"
            - "%netgen_block_manager.api.csrf_token_id%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_collection_results:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetCollectionResultsListener
        arguments:
            - "@netgen_block_manager.collection.result_loader"
            - "@netgen_block_manager.api.service.block"
            - "%netgen_block_manager.collection.max_limit%"
            - "%netgen_block_manager.block_view.collection_results_contexts%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.get_twig_block_content:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\BlockView\GetTwigBlockContentListener
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.invalidation:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\InvalidationListener
        arguments:
            - "@netgen_block_manager.http_cache.fos.cache_manager"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.cacheable_view:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\CacheableViewListener
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.layout_response:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\LayoutResponseListener
        arguments:
            - "@netgen_block_manager.http_cache.tagger"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.http_cache.block_response:
        class: Netgen\Bundle\BlockManagerBundle\EventListener\HttpCache\BlockResponseListener
        arguments:
            - "@netgen_block_manager.http_cache.tagger"
        tags:
            - { name: kernel.event_subscriber }
