parameters:
    netgen_block_manager.layout.form.create.class: Netgen\BlockManager\Layout\Form\CreateType

services:
    netgen_block_manager.layout.form.create:
        class: "%netgen_block_manager.layout.form.create.class%"
        arguments:
            - "@netgen_block_manager.configuration.registry.layout_type"
        tags:
            - { name: form.type }
