services:
    netgen_block_manager.http_cache.fos.cache_manager:
        synthetic: true
        public: true

    netgen_block_manager.http_cache.client:
        alias: netgen_block_manager.http_cache.client.varnish
        public: true

    netgen_block_manager.http_cache.client.varnish:
        class: Netgen\BlockManager\HttpCache\VarnishClient
        public: false
        arguments:
            - "@netgen_block_manager.http_cache.fos.cache_manager"
            - "@netgen_block_manager.http_cache.layout.id_provider"

    netgen_block_manager.http_cache.client.null:
        class: Netgen\BlockManager\HttpCache\NullClient
        public: false

    netgen_block_manager.http_cache.tagger:
        class: Netgen\BlockManager\HttpCache\Tagger
        public: false

    # BLOCK

    netgen_block_manager.http_cache.block.cacheable_resolver:
        class: Netgen\BlockManager\HttpCache\Block\CacheableResolver
        public: false

    netgen_block_manager.http_cache.block.cacheable_resolver.voter.container:
        class: Netgen\BlockManager\HttpCache\Block\CacheableResolver\ContainerVoter
        public: false
        tags:
            - { name: netgen_block_manager.http_cache.block.cacheable_resolver.voter, priority: 0 }

    # LAYOUT

    netgen_block_manager.http_cache.layout.id_provider:
        class: Netgen\BlockManager\HttpCache\Layout\IdProvider
        public: false
        arguments:
            - "@netgen_block_manager.api.service.layout"
