services:
    netgen_block_manager.http_cache.fos.cache_manager:
        synthetic: true

    netgen_block_manager.http_cache.client:
        alias: netgen_block_manager.http_cache.client.fos

    netgen_block_manager.http_cache.client.fos:
        class: Netgen\BlockManager\HttpCache\FOSClient
        arguments:
            - "@netgen_block_manager.http_cache.fos.cache_manager"
            - "@netgen_block_manager.http_cache.layout.id_provider"

    netgen_block_manager.http_cache.client.null:
        class: Netgen\BlockManager\HttpCache\NullClient

    netgen_block_manager.http_cache.tagger:
        class: Netgen\BlockManager\HttpCache\Tagger

    # BLOCK

    netgen_block_manager.http_cache.block.cacheable_resolver:
        class: Netgen\BlockManager\HttpCache\Block\CacheableResolver

    netgen_block_manager.http_cache.block.cacheable_resolver.voter.container:
        class: Netgen\BlockManager\HttpCache\Block\CacheableResolver\ContainerVoter
        arguments:
            - "@netgen_block_manager.http_cache.block.cacheable_resolver"
        tags:
            - { name: netgen_block_manager.http_cache.block.cacheable_resolver.voter }

    netgen_block_manager.http_cache.block.cacheable_resolver.voter.contextual_block:
        class: Netgen\BlockManager\HttpCache\Block\CacheableResolver\ContextualBlockVoter
        tags:
            - { name: netgen_block_manager.http_cache.block.cacheable_resolver.voter }

    netgen_block_manager.http_cache.block.cacheable_resolver.voter.contextual_query:
        class: Netgen\BlockManager\HttpCache\Block\CacheableResolver\ContextualQueryVoter
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: netgen_block_manager.http_cache.block.cacheable_resolver.voter }

    # LAYOUT

    netgen_block_manager.http_cache.layout.id_provider:
        class: Netgen\BlockManager\HttpCache\Layout\IdProvider
        arguments:
            - "@netgen_block_manager.api.service.layout"
