parameters:
    netgen_block_manager.item.item_builder.class: Netgen\BlockManager\Item\ItemBuilder
    netgen_block_manager.item.registry.value_loader.class: Netgen\BlockManager\Item\Registry\ValueLoaderRegistry

services:
    netgen_block_manager.item.item_builder:
        class: "%netgen_block_manager.item.item_builder.class%"
        arguments:
            - "@netgen_block_manager.item.registry.value_loader"
            - []

    netgen_block_manager.item.registry.value_loader:
        class: "%netgen_block_manager.item.registry.value_loader.class%"
