services:
    netgen_block_manager.item.item_builder:
        class: Netgen\BlockManager\Item\CmsItemBuilder
        public: true
        arguments:
            - []

    netgen_block_manager.item.item_loader:
        class: Netgen\BlockManager\Item\CmsItemLoader
        public: true
        arguments:
            - "@netgen_block_manager.item.item_builder"
            - []

    netgen_block_manager.item.url_generator:
        class: Netgen\BlockManager\Item\UrlGenerator
        public: true
        arguments:
            - []

    netgen_block_manager.item.registry.value_type:
        class: Netgen\BlockManager\Item\Registry\ValueTypeRegistry
        public: true

    netgen_block_manager.item.value_loader.null:
        class: Netgen\BlockManager\Item\ValueLoader\NullValueLoader
        public: false
        tags:
            - { name: netgen_block_manager.item.value_loader, value_type: "null" }

    netgen_block_manager.item.value_url_generator.null:
        class: Netgen\BlockManager\Item\ValueUrlGenerator\NullValueUrlGenerator
        public: false
        tags:
            - { name: netgen_block_manager.item.value_url_generator, value_type: "null" }
