services:
    netgen_block_manager.locale.provider:
        alias: netgen_block_manager.locale.provider.default
        public: false

    netgen_block_manager.locale.provider.default:
        class: Netgen\BlockManager\Locale\LocaleProvider
        public: false
