parameters:
    netgen_block_manager.normalizer.value_list.class: Netgen\BlockManager\Serializer\Normalizer\ValueListNormalizer
    netgen_block_manager.normalizer.view.class: Netgen\BlockManager\Serializer\Normalizer\ViewNormalizer
    netgen_block_manager.normalizer.form_view.class: Netgen\BlockManager\Serializer\Normalizer\FormViewNormalizer
    netgen_block_manager.normalizer.exception.class: Netgen\BlockManager\Serializer\Normalizer\ExceptionNormalizer

    netgen_block_manager.normalizer.v1.block.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\BlockNormalizer
    netgen_block_manager.normalizer.v1.collection_reference.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionReferenceNormalizer
    netgen_block_manager.normalizer.v1.layout.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\LayoutNormalizer
    netgen_block_manager.normalizer.v1.collection.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionNormalizer
    netgen_block_manager.normalizer.v1.collection_item.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionItemNormalizer
    netgen_block_manager.normalizer.v1.collection_query.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionQueryNormalizer

    netgen_block_manager.normalizer.v1.collection_result.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionResultNormalizer
    netgen_block_manager.normalizer.v1.collection_result_item.class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionResultItemNormalizer

    netgen_block_manager.normalizer.v1.block_type.class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\BlockTypeNormalizer
    netgen_block_manager.normalizer.v1.block_type_group.class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\BlockTypeGroupNormalizer
    netgen_block_manager.normalizer.v1.layout_type.class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\LayoutTypeNormalizer
    netgen_block_manager.normalizer.v1.source.class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\SourceNormalizer
    netgen_block_manager.normalizer.v1.source_query.class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\SourceQueryNormalizer

services:
    netgen_block_manager.normalizer.value_list:
        class: "%netgen_block_manager.normalizer.value_list.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.view:
        class: "%netgen_block_manager.normalizer.view.class%"
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.form_view:
        class: "%netgen_block_manager.normalizer.form_view.class%"
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: "%netgen_block_manager.normalizer.exception.class%"
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block:
        class: "%netgen_block_manager.normalizer.v1.block.class%"
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_reference:
        class: "%netgen_block_manager.normalizer.v1.collection_reference.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout:
        class: "%netgen_block_manager.normalizer.v1.layout.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection:
        class: "%netgen_block_manager.normalizer.v1.collection.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_item:
        class: "%netgen_block_manager.normalizer.v1.collection_item.class%"
        arguments:
            - "@netgen_block_manager.item.item_builder"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_query:
        class: "%netgen_block_manager.normalizer.v1.collection_query.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result:
        class: "%netgen_block_manager.normalizer.v1.collection_result.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result_item:
        class: "%netgen_block_manager.normalizer.v1.collection_result_item.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type:
        class: "%netgen_block_manager.normalizer.v1.block_type.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type_group:
        class: "%netgen_block_manager.normalizer.v1.block_type_group.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout_type:
        class: "%netgen_block_manager.normalizer.v1.layout_type.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.source:
        class: "%netgen_block_manager.normalizer.v1.source.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.source_query:
        class: "%netgen_block_manager.normalizer.v1.source_query.class%"
        tags:
            - { name: serializer.normalizer }
