services:
    netgen_block_manager.normalizer.value:
        class: Netgen\BlockManager\Serializer\Normalizer\ValueNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.view:
        class: Netgen\BlockManager\Serializer\Normalizer\ViewNormalizer
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.form_view:
        class: Netgen\BlockManager\Serializer\Normalizer\FormViewNormalizer
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: Netgen\BlockManager\Serializer\Normalizer\ExceptionNormalizer
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.parameter_value:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\ParameterValueNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockNormalizer
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.placeholder:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\PlaceholderNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_reference:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionReferenceNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\LayoutNormalizer
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_item:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionItemNormalizer
        arguments:
            - "@netgen_block_manager.item.item_loader"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_query:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionQueryNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result_set:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionResultSetNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionResultNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockTypeNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type_group:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockTypeGroupNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout_type:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\LayoutTypeNormalizer
        tags:
            - { name: serializer.normalizer }
