services:
    netgen_block_manager.normalizer.value:
        class: Netgen\BlockManager\Serializer\Normalizer\ValueNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.view:
        class: Netgen\BlockManager\Serializer\Normalizer\ViewNormalizer
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.form_view:
        class: Netgen\BlockManager\Serializer\Normalizer\FormViewNormalizer
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: Netgen\BlockManager\Serializer\Normalizer\ExceptionNormalizer
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.parameter_value:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\ParameterValueNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\BlockNormalizer
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_reference:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionReferenceNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\LayoutNormalizer
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_item:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionItemNormalizer
        arguments:
            - "@netgen_block_manager.item.item_loader"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_query:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionQueryNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result_set:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionResultSetNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result:
        class: Netgen\BlockManager\Serializer\V1\ValueNormalizer\CollectionResultNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type:
        class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\BlockTypeNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type_group:
        class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\BlockTypeGroupNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout_type:
        class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\LayoutTypeNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.source:
        class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\SourceNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.source_query:
        class: Netgen\BlockManager\Serializer\V1\ConfigurationNormalizer\SourceQueryNormalizer
        tags:
            - { name: serializer.normalizer }
