parameters:
    netgen_block_manager.parameters.registry.parameter_type.class: Netgen\BlockManager\Parameters\Registry\ParameterTypeRegistry
    netgen_block_manager.parameters.registry.parameter_filter.class: Netgen\BlockManager\Parameters\Registry\ParameterFilterRegistry

    netgen_block_manager.parameters.parameter_type.text_line.class: Netgen\BlockManager\Parameters\ParameterType\TextLine
    netgen_block_manager.parameters.parameter_type.identifier.class: Netgen\BlockManager\Parameters\ParameterType\Identifier
    netgen_block_manager.parameters.parameter_type.integer.class: Netgen\BlockManager\Parameters\ParameterType\Integer
    netgen_block_manager.parameters.parameter_type.range.class: Netgen\BlockManager\Parameters\ParameterType\Range
    netgen_block_manager.parameters.parameter_type.number.class: Netgen\BlockManager\Parameters\ParameterType\Number
    netgen_block_manager.parameters.parameter_type.boolean.class: Netgen\BlockManager\Parameters\ParameterType\Boolean
    netgen_block_manager.parameters.parameter_type.text.class: Netgen\BlockManager\Parameters\ParameterType\Text
    netgen_block_manager.parameters.parameter_type.html.class: Netgen\BlockManager\Parameters\ParameterType\Html
    netgen_block_manager.parameters.parameter_type.choice.class: Netgen\BlockManager\Parameters\ParameterType\Choice
    netgen_block_manager.parameters.parameter_type.url.class: Netgen\BlockManager\Parameters\ParameterType\Url
    netgen_block_manager.parameters.parameter_type.email.class: Netgen\BlockManager\Parameters\ParameterType\Email
    netgen_block_manager.parameters.parameter_type.item_link.class: Netgen\BlockManager\Parameters\ParameterType\ItemLink
    netgen_block_manager.parameters.parameter_type.link.class: Netgen\BlockManager\Parameters\ParameterType\Link
    netgen_block_manager.parameters.parameter_type.compound.boolean.class: Netgen\BlockManager\Parameters\ParameterType\Compound\Boolean

    netgen_block_manager.parameters.parameter_filter.html.html_purifier.class: Netgen\BlockManager\Parameters\Filter\Html\HtmlPurifierFilter

    netgen_block_manager.parameters.parameter_handler.text_line.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\TextLine
    netgen_block_manager.parameters.parameter_handler.identifier.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Identifier
    netgen_block_manager.parameters.parameter_handler.integer.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Integer
    netgen_block_manager.parameters.parameter_handler.range.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Range
    netgen_block_manager.parameters.parameter_handler.number.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Number
    netgen_block_manager.parameters.parameter_handler.boolean.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Boolean
    netgen_block_manager.parameters.parameter_handler.text.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Text
    netgen_block_manager.parameters.parameter_handler.html.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Html
    netgen_block_manager.parameters.parameter_handler.choice.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Choice
    netgen_block_manager.parameters.parameter_handler.url.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Url
    netgen_block_manager.parameters.parameter_handler.email.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Email
    netgen_block_manager.parameters.parameter_handler.item_link.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\ItemLink
    netgen_block_manager.parameters.parameter_handler.link.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Link
    netgen_block_manager.parameters.parameter_handler.compound.boolean.class: Netgen\BlockManager\Parameters\FormMapper\ParameterHandler\Compound\Boolean

    netgen_block_manager.parameters.form_mapper.class: Netgen\BlockManager\Parameters\FormMapper\FormMapper

    netgen_block_manager.parameters.form.parameters.class: Netgen\BlockManager\Parameters\Form\ParametersType
    netgen_block_manager.parameters.form.ngbm_compound_boolean.class: Netgen\BlockManager\Parameters\Form\CompoundBooleanType

services:
    netgen_block_manager.parameters.registry.parameter_type:
        class: "%netgen_block_manager.parameters.registry.parameter_type.class%"

    netgen_block_manager.parameters.registry.parameter_filter:
        class: "%netgen_block_manager.parameters.registry.parameter_filter.class%"

    netgen_block_manager.parameters.parameter_filter.html.html_purifier:
        class: "%netgen_block_manager.parameters.parameter_filter.html.html_purifier.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_filter, parameter_type: html }

    netgen_block_manager.parameters.parameter_type.text_line:
        class: "%netgen_block_manager.parameters.parameter_type.text_line.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.identifier:
        class: "%netgen_block_manager.parameters.parameter_type.identifier.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.integer:
        class: "%netgen_block_manager.parameters.parameter_type.integer.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.range:
        class: "%netgen_block_manager.parameters.parameter_type.range.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.number:
        class: "%netgen_block_manager.parameters.parameter_type.number.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.boolean:
        class: "%netgen_block_manager.parameters.parameter_type.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.text:
        class: "%netgen_block_manager.parameters.parameter_type.text.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.html:
        class: "%netgen_block_manager.parameters.parameter_type.html.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.choice:
        class: "%netgen_block_manager.parameters.parameter_type.choice.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.url:
        class: "%netgen_block_manager.parameters.parameter_type.url.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.email:
        class: "%netgen_block_manager.parameters.parameter_type.email.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.item_link:
        class: "%netgen_block_manager.parameters.parameter_type.item_link.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.link:
        class: "%netgen_block_manager.parameters.parameter_type.link.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.compound.boolean:
        class: "%netgen_block_manager.parameters.parameter_type.compound.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_handler.text_line:
        class: "%netgen_block_manager.parameters.parameter_handler.text_line.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: text_line }

    netgen_block_manager.parameters.parameter_handler.identifier:
        class: "%netgen_block_manager.parameters.parameter_handler.identifier.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: identifier }

    netgen_block_manager.parameters.parameter_handler.integer:
        class: "%netgen_block_manager.parameters.parameter_handler.integer.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: integer }

    netgen_block_manager.parameters.parameter_handler.range:
        class: "%netgen_block_manager.parameters.parameter_handler.range.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: range }

    netgen_block_manager.parameters.parameter_handler.number:
        class: "%netgen_block_manager.parameters.parameter_handler.number.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: number }

    netgen_block_manager.parameters.parameter_handler.boolean:
        class: "%netgen_block_manager.parameters.parameter_handler.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: boolean }

    netgen_block_manager.parameters.parameter_handler.text:
        class: "%netgen_block_manager.parameters.parameter_handler.text.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: text }

    netgen_block_manager.parameters.parameter_handler.html:
        class: "%netgen_block_manager.parameters.parameter_handler.html.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: html }

    netgen_block_manager.parameters.parameter_handler.choice:
        class: "%netgen_block_manager.parameters.parameter_handler.choice.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: choice }

    netgen_block_manager.parameters.parameter_handler.url:
        class: "%netgen_block_manager.parameters.parameter_handler.url.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: url }

    netgen_block_manager.parameters.parameter_handler.email:
        class: "%netgen_block_manager.parameters.parameter_handler.email.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: email }

    netgen_block_manager.parameters.parameter_handler.item_link:
        class: "%netgen_block_manager.parameters.parameter_handler.item_link.class%"
        arguments:
            - "%netgen_block_manager.item.value_types%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: item_link }

    netgen_block_manager.parameters.parameter_handler.link:
        class: "%netgen_block_manager.parameters.parameter_handler.link.class%"
        arguments:
            - "@netgen_block_manager.parameters.parameter_type.link"
            - "%netgen_block_manager.item.value_types%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: link }

    netgen_block_manager.parameters.parameter_handler.compound.boolean:
        class: "%netgen_block_manager.parameters.parameter_handler.compound.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: compound_boolean }

    netgen_block_manager.parameters.form_mapper:
        class: "%netgen_block_manager.parameters.form_mapper.class%"
        arguments:
            - []

    netgen_block_manager.parameters.form.parameters:
        class: "%netgen_block_manager.parameters.form.parameters.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
        tags:
            - { name: form.type }


    netgen_block_manager.parameters.form.ngbm_compound_boolean:
        class: "%netgen_block_manager.parameters.form.ngbm_compound_boolean.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
        tags:
            - { name: form.type }
