parameters:
    netgen_block_manager.parameters.registry.parameter_type.class: Netgen\BlockManager\Parameters\Registry\ParameterTypeRegistry
    netgen_block_manager.parameters.registry.form_mapper.class: Netgen\BlockManager\Parameters\Registry\FormMapperRegistry
    netgen_block_manager.parameters.registry.parameter_filter.class: Netgen\BlockManager\Parameters\Registry\ParameterFilterRegistry

    netgen_block_manager.parameters.parameter_builder.class: Netgen\BlockManager\Parameters\ParameterBuilder

    netgen_block_manager.parameters.parameter_type.text_line.class: Netgen\BlockManager\Parameters\ParameterType\TextLineType
    netgen_block_manager.parameters.parameter_type.identifier.class: Netgen\BlockManager\Parameters\ParameterType\IdentifierType
    netgen_block_manager.parameters.parameter_type.integer.class: Netgen\BlockManager\Parameters\ParameterType\IntegerType
    netgen_block_manager.parameters.parameter_type.range.class: Netgen\BlockManager\Parameters\ParameterType\RangeType
    netgen_block_manager.parameters.parameter_type.number.class: Netgen\BlockManager\Parameters\ParameterType\NumberType
    netgen_block_manager.parameters.parameter_type.boolean.class: Netgen\BlockManager\Parameters\ParameterType\BooleanType
    netgen_block_manager.parameters.parameter_type.text.class: Netgen\BlockManager\Parameters\ParameterType\TextType
    netgen_block_manager.parameters.parameter_type.html.class: Netgen\BlockManager\Parameters\ParameterType\HtmlType
    netgen_block_manager.parameters.parameter_type.choice.class: Netgen\BlockManager\Parameters\ParameterType\ChoiceType
    netgen_block_manager.parameters.parameter_type.url.class: Netgen\BlockManager\Parameters\ParameterType\UrlType
    netgen_block_manager.parameters.parameter_type.email.class: Netgen\BlockManager\Parameters\ParameterType\EmailType
    netgen_block_manager.parameters.parameter_type.item_link.class: Netgen\BlockManager\Parameters\ParameterType\ItemLinkType
    netgen_block_manager.parameters.parameter_type.link.class: Netgen\BlockManager\Parameters\ParameterType\LinkType
    netgen_block_manager.parameters.parameter_type.compound.boolean.class: Netgen\BlockManager\Parameters\ParameterType\Compound\BooleanType

    netgen_block_manager.parameters.parameter_filter.html.html_purifier.class: Netgen\BlockManager\Parameters\Filter\Html\HtmlPurifierFilter

    netgen_block_manager.parameters.form.mapper.text_line.class: Netgen\BlockManager\Parameters\Form\Mapper\TextLineMapper
    netgen_block_manager.parameters.form.mapper.identifier.class: Netgen\BlockManager\Parameters\Form\Mapper\IdentifierMapper
    netgen_block_manager.parameters.form.mapper.integer.class: Netgen\BlockManager\Parameters\Form\Mapper\IntegerMapper
    netgen_block_manager.parameters.form.mapper.range.class: Netgen\BlockManager\Parameters\Form\Mapper\RangeMapper
    netgen_block_manager.parameters.form.mapper.number.class: Netgen\BlockManager\Parameters\Form\Mapper\NumberMapper
    netgen_block_manager.parameters.form.mapper.boolean.class: Netgen\BlockManager\Parameters\Form\Mapper\BooleanMapper
    netgen_block_manager.parameters.form.mapper.text.class: Netgen\BlockManager\Parameters\Form\Mapper\TextMapper
    netgen_block_manager.parameters.form.mapper.html.class: Netgen\BlockManager\Parameters\Form\Mapper\HtmlMapper
    netgen_block_manager.parameters.form.mapper.choice.class: Netgen\BlockManager\Parameters\Form\Mapper\ChoiceMapper
    netgen_block_manager.parameters.form.mapper.url.class: Netgen\BlockManager\Parameters\Form\Mapper\UrlMapper
    netgen_block_manager.parameters.form.mapper.email.class: Netgen\BlockManager\Parameters\Form\Mapper\EmailMapper
    netgen_block_manager.parameters.form.mapper.item_link.class: Netgen\BlockManager\Parameters\Form\Mapper\ItemLinkMapper
    netgen_block_manager.parameters.form.mapper.link.class: Netgen\BlockManager\Parameters\Form\Mapper\LinkMapper
    netgen_block_manager.parameters.form.mapper.compound.boolean.class: Netgen\BlockManager\Parameters\Form\Mapper\Compound\BooleanMapper

    netgen_block_manager.parameters.form.type.parameters.class: Netgen\BlockManager\Parameters\Form\Type\ParametersType

services:
    # Registries

    netgen_block_manager.parameters.registry.parameter_type:
        class: "%netgen_block_manager.parameters.registry.parameter_type.class%"

    netgen_block_manager.parameters.registry.form_mapper:
        class: "%netgen_block_manager.parameters.registry.form_mapper.class%"

    netgen_block_manager.parameters.registry.parameter_filter:
        class: "%netgen_block_manager.parameters.registry.parameter_filter.class%"

    # Builders

    netgen_block_manager.parameters.parameter_builder:
        class: "%netgen_block_manager.parameters.parameter_builder.class%"
        arguments:
            - "@netgen_block_manager.parameters.registry.parameter_type"
        # Builder is a one use & discard object, hence shared: false
        shared: false

    # Filters

    netgen_block_manager.parameters.parameter_filter.html.html_purifier:
        class: "%netgen_block_manager.parameters.parameter_filter.html.html_purifier.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_filter, type: html }

    # Parameter types

    netgen_block_manager.parameters.parameter_type.text_line:
        class: "%netgen_block_manager.parameters.parameter_type.text_line.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.identifier:
        class: "%netgen_block_manager.parameters.parameter_type.identifier.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.integer:
        class: "%netgen_block_manager.parameters.parameter_type.integer.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.range:
        class: "%netgen_block_manager.parameters.parameter_type.range.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.number:
        class: "%netgen_block_manager.parameters.parameter_type.number.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.boolean:
        class: "%netgen_block_manager.parameters.parameter_type.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.text:
        class: "%netgen_block_manager.parameters.parameter_type.text.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.html:
        class: "%netgen_block_manager.parameters.parameter_type.html.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.choice:
        class: "%netgen_block_manager.parameters.parameter_type.choice.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.url:
        class: "%netgen_block_manager.parameters.parameter_type.url.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.email:
        class: "%netgen_block_manager.parameters.parameter_type.email.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.item_link:
        class: "%netgen_block_manager.parameters.parameter_type.item_link.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.link:
        class: "%netgen_block_manager.parameters.parameter_type.link.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.parameter_type.compound.boolean:
        class: "%netgen_block_manager.parameters.parameter_type.compound.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    # Form mappers

    netgen_block_manager.parameters.form.mapper.text_line:
        class: "%netgen_block_manager.parameters.form.mapper.text_line.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: text_line }

    netgen_block_manager.parameters.form.mapper.identifier:
        class: "%netgen_block_manager.parameters.form.mapper.identifier.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: identifier }

    netgen_block_manager.parameters.form.mapper.integer:
        class: "%netgen_block_manager.parameters.form.mapper.integer.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: integer }

    netgen_block_manager.parameters.form.mapper.range:
        class: "%netgen_block_manager.parameters.form.mapper.range.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: range }

    netgen_block_manager.parameters.form.mapper.number:
        class: "%netgen_block_manager.parameters.form.mapper.number.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: number }

    netgen_block_manager.parameters.form.mapper.boolean:
        class: "%netgen_block_manager.parameters.form.mapper.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: boolean }

    netgen_block_manager.parameters.form.mapper.text:
        class: "%netgen_block_manager.parameters.form.mapper.text.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: text }

    netgen_block_manager.parameters.form.mapper.html:
        class: "%netgen_block_manager.parameters.form.mapper.html.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: html }

    netgen_block_manager.parameters.form.mapper.choice:
        class: "%netgen_block_manager.parameters.form.mapper.choice.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: choice }

    netgen_block_manager.parameters.form.mapper.url:
        class: "%netgen_block_manager.parameters.form.mapper.url.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: url }

    netgen_block_manager.parameters.form.mapper.email:
        class: "%netgen_block_manager.parameters.form.mapper.email.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: email }

    netgen_block_manager.parameters.form.mapper.item_link:
        class: "%netgen_block_manager.parameters.form.mapper.item_link.class%"
        arguments:
            - "%netgen_block_manager.item.value_types%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: item_link }

    netgen_block_manager.parameters.form.mapper.link:
        class: "%netgen_block_manager.parameters.form.mapper.link.class%"
        arguments:
            - "%netgen_block_manager.item.value_types%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: link }

    netgen_block_manager.parameters.form.mapper.compound.boolean:
        class: "%netgen_block_manager.parameters.form.mapper.compound.boolean.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: compound_boolean }

    # Form

    netgen_block_manager.parameters.form.type.parameters:
        class: "%netgen_block_manager.parameters.form.type.parameters.class%"
        arguments:
            - "@netgen_block_manager.parameters.registry.form_mapper"
        tags:
            - { name: form.type }
