parameters:
    netgen_block_manager.param_converter.block.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\BlockParamConverter
    netgen_block_manager.param_converter.layout.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\LayoutParamConverter
    netgen_block_manager.param_converter.collection.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\CollectionParamConverter
    netgen_block_manager.param_converter.collection_item.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\CollectionItemParamConverter
    netgen_block_manager.param_converter.collection_query.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\CollectionQueryParamConverter

services:
    netgen_block_manager.param_converter.block:
        class: "%netgen_block_manager.param_converter.block.class%"
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: request.param_converter }

    netgen_block_manager.param_converter.layout:
        class: "%netgen_block_manager.param_converter.layout.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: request.param_converter }

    netgen_block_manager.param_converter.collection:
        class: "%netgen_block_manager.param_converter.collection.class%"
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: request.param_converter }

    netgen_block_manager.param_converter.collection_item:
        class: "%netgen_block_manager.param_converter.collection_item.class%"
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: request.param_converter }

    netgen_block_manager.param_converter.collection_query:
        class: "%netgen_block_manager.param_converter.collection_query.class%"
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: request.param_converter }
