parameters:
    netgen_block_manager.collection.query.form.full_edit.class: Netgen\BlockManager\Collection\Query\Form\FullEditType

services:
    netgen_block_manager.collection.query.form.full_edit:
        class: "%netgen_block_manager.collection.query.form.full_edit.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
        tags:
            - { name: form.type }
