services:
    netgen_block_manager.security.csrf_validator:
        class: Netgen\Bundle\BlockManagerBundle\Security\CsrfTokenValidator
        public: false
        arguments:
            - "@security.csrf.token_manager"
