parameters:
    netgen_block_manager.controller.block_controller: 'ngbm_block:viewBlock'

services:
    netgen_block_manager.templating.global_variable:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\GlobalVariable
        arguments:
            - "@netgen_block_manager.configuration"
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.view.builder"

    netgen_block_manager.templating.twig.extension.rendering:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\RenderingExtension
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.templating.global_variable"
            - "@netgen_block_manager.view.renderer"
            - "@fragment.handler"
            - "%netgen_block_manager.controller.block_controller%"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: twig.extension }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.templating.twig.extension.item:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\ItemExtension
        arguments:
            - "@netgen_block_manager.item.item_loader"
            - "@netgen_block_manager.item.url_builder"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: twig.extension }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.templating.pagelayout_resolver.default:
        class: Netgen\Bundle\BlockManagerBundle\Templating\PageLayoutResolver
        arguments:
            - "%netgen_block_manager.pagelayout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.default
