parameters:
    netgen_block_manager.controller.block_controller: 'ngbm_block:viewBlock'

services:
    netgen_block_manager.templating.twig.runtime.container_loader:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\Loader\ContainerRuntimeLoader
        public: false
        deprecated: ~
        arguments:
            - "@service_container"

    netgen_block_manager.templating.global_variable:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\GlobalVariable
        public: false
        arguments:
            - "@netgen_block_manager.configuration"
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.view.view_builder"
            - "@request_stack"

    netgen_block_manager.templating.twig.extension.rendering:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\RenderingExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.rendering:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\RenderingRuntime
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.view.renderer.fragment"
            - "@netgen_block_manager.locale.provider"
            - "@request_stack"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.templating.twig.extension.item:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\ItemExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.item:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\ItemRuntime
        arguments:
            - "@netgen_block_manager.item.item_loader"
            - "@netgen_block_manager.item.url_builder"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.templating.pagelayout_resolver.default:
        class: Netgen\Bundle\BlockManagerBundle\Templating\PageLayoutResolver
        public: false
        arguments:
            - "%netgen_block_manager.pagelayout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.default
        public: false
