parameters:
    netgen_block_manager.templating.global_helper.class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\GlobalHelper
    netgen_block_manager.templating.twig.extension.class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\NetgenBlockManagerExtension
    netgen_block_manager.templating.pagelayout_resolver.default.class: Netgen\Bundle\BlockManagerBundle\Templating\PageLayoutResolver

services:
    netgen_block_manager.templating.global_helper:
        class: "%netgen_block_manager.templating.global_helper.class%"

    netgen_block_manager.templating.twig.extension:
        class: "%netgen_block_manager.templating.twig.extension.class%"
        arguments:
            - "@netgen_block_manager.block.registry.block_definition"
            - "@netgen_block_manager.templating.global_helper"
            - "@netgen_block_manager.view.renderer"
            - "@fragment.handler"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: twig.extension }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.templating.pagelayout_resolver.default:
        class: "%netgen_block_manager.templating.pagelayout_resolver.default.class%"
        arguments:
            - "%netgen_block_manager.pagelayout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.default
