parameters:
    netgen_block_manager.controller.block_controller: 'ngbm_block:viewBlockById'
    netgen_block_manager.templating.global_variable.class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\GlobalVariable
    netgen_block_manager.templating.twig.extension.rendering.class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\RenderingExtension
    netgen_block_manager.templating.pagelayout_resolver.default.class: Netgen\Bundle\BlockManagerBundle\Templating\PageLayoutResolver

services:
    netgen_block_manager.templating.global_variable:
        class: "%netgen_block_manager.templating.global_variable.class%"
        arguments:
            - "@netgen_block_manager.configuration"
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.view.builder"

    netgen_block_manager.templating.twig.extension.rendering:
        class: "%netgen_block_manager.templating.twig.extension.rendering.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.templating.global_variable"
            - "@netgen_block_manager.view.renderer"
            - "@fragment.handler"
            - "%netgen_block_manager.controller.block_controller%"
            - "@?logger"
        calls:
            - [setDebug, ["%kernel.debug%"]]
        tags:
            - { name: twig.extension }
            - { name: monolog.logger, channel: ngbm }

    netgen_block_manager.templating.pagelayout_resolver.default:
        class: "%netgen_block_manager.templating.pagelayout_resolver.default.class%"
        arguments:
            - "%netgen_block_manager.pagelayout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.default
