parameters:
    netgen_block_manager.validator.block_view_type.class: Netgen\BlockManager\Validator\BlockViewTypeValidator
    netgen_block_manager.validator.block_definition.class: Netgen\BlockManager\Validator\BlockDefinitionValidator
    netgen_block_manager.validator.query_type.class: Netgen\BlockManager\Validator\QueryTypeValidator
    netgen_block_manager.validator.value_type.class: Netgen\BlockManager\Validator\ValueTypeValidator

services:
    netgen_block_manager.validator.block_view_type:
        class: "%netgen_block_manager.validator.block_view_type.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_view_type }

    netgen_block_manager.validator.block_definition:
        class: "%netgen_block_manager.validator.block_definition.class%"
        arguments:
            - "@netgen_block_manager.block.registry.block_definition"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_definition }

    netgen_block_manager.validator.query_type:
        class: "%netgen_block_manager.validator.query_type.class%"
        arguments:
            - "@netgen_block_manager.collection.registry.query_type"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_query_type }

    netgen_block_manager.validator.value_type:
        class: "%netgen_block_manager.validator.value_type.class%"
        arguments:
            - "@netgen_block_manager.collection.registry.value_loader"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_value_type }
