parameters:
    netgen_block_manager.validator.block_view_type.class: Netgen\BlockManager\Validator\BlockViewTypeValidator
    netgen_block_manager.validator.value_type.class: Netgen\BlockManager\Validator\ValueTypeValidator

services:
    netgen_block_manager.validator.block_view_type:
        class: "%netgen_block_manager.validator.block_view_type.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_view_type }

    netgen_block_manager.validator.value_type:
        class: "%netgen_block_manager.validator.value_type.class%"
        arguments:
            - "@netgen_block_manager.value.registry.value_loader"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_value_type }
