parameters:
    netgen_block_manager.validator.layout_name.class: Netgen\BlockManager\Validator\LayoutNameValidator
    netgen_block_manager.validator.block_view_type.class: Netgen\BlockManager\Validator\BlockViewTypeValidator
    netgen_block_manager.validator.block_item_view_type.class: Netgen\BlockManager\Validator\BlockItemViewTypeValidator
    netgen_block_manager.validator.value_type.class: Netgen\BlockManager\Validator\ValueTypeValidator
    netgen_block_manager.validator.item_link.class: Netgen\BlockManager\Validator\ItemLinkValidator
    netgen_block_manager.validator.link.class: Netgen\BlockManager\Validator\Parameters\LinkValidator

    netgen_block_manager.validator.parameter_struct.class: Netgen\BlockManager\Validator\Structs\ParameterStructValidator
    netgen_block_manager.validator.block_update_struct.class: Netgen\BlockManager\Validator\Structs\BlockUpdateStructValidator
    netgen_block_manager.validator.query_update_struct.class: Netgen\BlockManager\Validator\Structs\QueryUpdateStructValidator

services:
    netgen_block_manager.validator.layout_name:
        class: "%netgen_block_manager.validator.layout_name.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_layout_name }

    netgen_block_manager.validator.block_view_type:
        class: "%netgen_block_manager.validator.block_view_type.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_view_type }

    netgen_block_manager.validator.block_item_view_type:
        class: "%netgen_block_manager.validator.block_item_view_type.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_item_view_type }

    netgen_block_manager.validator.value_type:
        class: "%netgen_block_manager.validator.value_type.class%"
        arguments:
            - "%netgen_block_manager.item.value_types%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_value_type }

    netgen_block_manager.validator.item_link:
        class: "%netgen_block_manager.validator.item_link.class%"
        arguments:
            - "@netgen_block_manager.item.item_loader"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_item_link }

    netgen_block_manager.validator.link:
        class: "%netgen_block_manager.validator.link.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_link }

    netgen_block_manager.validator.parameter_struct:
        class: "%netgen_block_manager.validator.parameter_struct.class%"
        arguments:
            - "@netgen_block_manager.parameters.registry.parameter_type"
            - "@netgen_block_manager.parameters.registry.parameter_filter"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_parameter_struct }

    netgen_block_manager.validator.block_update_struct:
        class: "%netgen_block_manager.validator.block_update_struct.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_update_struct }

    netgen_block_manager.validator.query_update_struct:
        class: "%netgen_block_manager.validator.query_update_struct.class%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_query_update_struct }
