services:
    # Services tagged with 'netgen_block_manager.transfer.serializer.visitor' register to this one
    netgen_block_manager.transfer.serializer.visitor.aggregate:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Aggregate
        public: false
        arguments:
            - []

    netgen_block_manager.transfer.serializer.visitor.block:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Block
        public: false
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.collection:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Collection
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.condition:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Condition
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.config:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Config
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.item:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Item
        public: false
        arguments:
            - "@netgen_block_manager.item.item_loader"
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.layout:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Layout
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.parameter:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Parameter
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.placeholder:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Placeholder
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.query:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Query
        public: false
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.rule:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Rule
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.target:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Target
        public: false
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }

    netgen_block_manager.transfer.serializer.visitor.zone:
        class: Netgen\BlockManager\Transfer\Output\Visitor\Zone
        public: false
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: netgen_block_manager.transfer.serializer.visitor }
