parameters:
    netgen_block_manager.app.pagelayout: '@@NetgenBlockManagerAdmin/app/pagelayout.html.twig'
    netgen_block_manager.admin.csrf_token_id: ngbm_admin
    netgen_block_manager.admin.pagelayout: '@@NetgenBlockManagerAdmin/admin/pagelayout.html.twig'
