# Redirect routes, must be specified BEFORE regular routes

_ngbm_admin_redirect:
    resource: "admin/redirects.yml"

# Regular routes follow

ngbm_admin:
    path: /admin/
    methods: [GET]
    defaults:
        _controller: "FrameworkBundle:Redirect:redirect"
        route: ngbm_admin_layout_resolver_index
        permanent: true

_ngbm_admin_layout_resolver:
    resource: "admin/layout_resolver.yml"
    prefix: /admin/layout_resolver

_ngbm_admin_layouts:
    resource: "admin/layouts.yml"
    prefix: /admin/layouts

_ngbm_admin_shared_layouts:
    resource: "admin/shared_layouts.yml"
    prefix: /admin/shared_layouts
