ngbm_app_no_slash:
    path: /app
    methods: [GET]
    defaults:
        _controller: "FrameworkBundle:Redirect:redirect"
        route: ngbm_app
        permanent: true

ngbm_app:
    path: /app/
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.app.index"

ngbm_app_layout_form_create:
    path: /app/layouts/form/create
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout.create_form"

ngbm_app_layout_form_edit:
    path: /app/layouts/{layoutId}/form/edit
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout.edit_form"

ngbm_app_layout_form_main_locale:
    path: /app/layouts/{layoutId}/form/main_locale
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout.set_main_locale_form"

ngbm_app_layout_form_add_locale:
    path: /app/layouts/{layoutId}/form/add_locale
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout.add_locale_form"

ngbm_app_layout_form_remove_locale:
    path: /app/layouts/{layoutId}/form/remove_locale
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout.remove_locale_form"

ngbm_app_block_edit:
    path: /app/{locale}/blocks/{blockId}/edit
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.app.block.edit"
        _ngbm_status: draft

ngbm_app_block_form_configure_translation:
    path: /app/{locale}/blocks/{blockId}/form/configure_translation
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.block.configure_translation_form"
        _ngbm_status: draft

ngbm_app_block_form_edit:
    path: /app/{locale}/blocks/{blockId}/form/edit/{formName}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.block.edit_form"
        _ngbm_status: draft

ngbm_app_block_form_edit_config:
    path: /app/{locale}/blocks/{blockId}/config/edit/{configKey}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.block.edit_config_form"
        _ngbm_status: draft
        configKey: null

ngbm_app_collection_collection_form_edit:
    path: /app/collections/{collectionId}/form/edit/full
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.collection.edit_collection_form"
        _ngbm_status: draft

ngbm_app_collection_form_edit_item_config:
    path: /app/collections/item/{itemId}/config/edit/{configKey}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.collection.edit_item_config_form"
        _ngbm_status: draft
        configKey: null

ngbm_app_collection_query_form_edit:
    path: /app/{locale}/collections/query/{queryId}/form/edit
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.collection.edit_query_form"
        _ngbm_status: draft
