ngbm_app_no_slash:
    path: /app
    methods: [GET]
    defaults:
        _controller: "FrameworkBundle:Redirect:redirect"
        route: ngbm_app
        permanent: true

ngbm_app:
    path: /app/
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.app.index:index"

ngbm_app_block_edit:
    path: /app/blocks/{blockId}/edit
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.app.block:edit"
        _ngbm_status: draft

ngbm_app_layout_form_create:
    path: /app/layouts/form/create
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout:layoutCreateForm"

ngbm_app_layout_form_edit:
    path: /app/layouts/{layoutId}/form/edit
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.layout:layoutEditForm"

ngbm_app_block_form_edit:
    path: /app/blocks/{blockId}/form/edit/{formName}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.block:editForm"
        _ngbm_status: draft

ngbm_app_block_form_edit_config:
    path: /app/blocks/{blockId}/config/edit/{configKey}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.block:editConfigForm"
        _ngbm_status: draft
        configKey: null

ngbm_app_collection_query_form_edit:
    path: /app/collections/query/{queryId}/form/edit/{formName}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.app.collection:queryEditForm"
        _ngbm_status: draft
