block_view:
    view:
        title:
            template: "NetgenBlockManagerBundle:block/view:title.html.twig"
            match:
                block\definition: title
        text:
            template: "NetgenBlockManagerBundle:block/view:text.html.twig"
            match:
                block\definition: text
        # Fallbacks for content blocks!
        twig_block:
            template: "NetgenBlockManagerBundle:block/view:twig_block.html.twig"
            match:
                block\definition: twig_block
        content:
            template: "NetgenBlockManagerBundle:block/view:content.html.twig"
            match:
                block\definition: content
    api_view:
        title:
            template: "NetgenBlockManagerBundle:api/block/view:title.html.twig"
            match:
                block\definition: title
                api_version: 1
        text:
            template: "NetgenBlockManagerBundle:api/block/view:text.html.twig"
            match:
                block\definition: text
                api_version: 1
        rich_text:
            template: "NetgenBlockManagerBundle:api/block/view:rich_text.html.twig"
            match:
                block\definition: rich_text
                api_version: 1
        html_snippet:
            template: "NetgenBlockManagerBundle:api/block/view:html_snippet.html.twig"
            match:
                block\definition: html_snippet
                api_version: 1
        list\list:
            template: "NetgenBlockManagerBundle:api/block/view/list:list.html.twig"
            match:
                block\definition: list
                block\view_type: list
                api_version: 1
        list\grid:
            template: "NetgenBlockManagerBundle:api/block/view/list:grid.html.twig"
            match:
                block\definition: list
                block\view_type: grid
                api_version: 1
        gallery:
            template: "NetgenBlockManagerBundle:api/block/view:gallery.html.twig"
            match:
                block\definition: gallery
                api_version: 1
        block:
            template: "NetgenBlockManagerBundle:api/block:view.html.twig"
            match:
                api_version: 1
