view:
    block_view:
        default:
            invalid:
                template: "@NetgenBlockManager/block/invalid_block.html.twig"
                match:
                    block\definition: "null"
        ajax:
            invalid:
                template: "@NetgenBlockManager/block/invalid_block.html.twig"
                match:
                    block\definition: "null"
        api:
            invalid:
                template: "@NetgenBlockManager/api/block/invalid_block.html.twig"
                match:
                    block\definition: "null"
