block_view:
    view:
        title_large:
            template: "NetgenBlockManagerBundle:block/view/title:large.html.twig"
            match:
                block_definition_identifier: title
                block_view_type: large
        title:
            template: "NetgenBlockManagerBundle:block/view/title:default.html.twig"
            match:
                block_definition_identifier: title
        paragraph_small:
            template: "NetgenBlockManagerBundle:block/view/paragraph:small.html.twig"
            match:
                block_definition_identifier: paragraph
                block_view_type: small
        paragraph:
            template: "NetgenBlockManagerBundle:block/view/paragraph:default.html.twig"
            match:
                block_definition_identifier: paragraph
    api_view:
        title:
            template: "NetgenBlockManagerBundle:api/block/view:title.html.twig"
            match:
                block_definition_identifier: title
                api_version: 1
        paragraph:
            template: "NetgenBlockManagerBundle:api/block/view:paragraph.html.twig"
            match:
                block_definition_identifier: paragraph
                api_version: 1
        block:
            template: "NetgenBlockManagerBundle:api/block:view.html.twig"
            match:
                api_version: 1
    api_edit:
        block:
            template: "NetgenBlockManagerBundle:api/block:edit.html.twig"
            match:
                api_version: 1
    api_form:
        block:
            template: "NetgenBlockManagerBundle:api/block/form:full.html.twig"
            match:
                api_version: 1
