block_view:
    view:
        title_large:
            template: "NetgenBlockManagerBundle:block/view/title:large.html.twig"
            match:
                block_definition_identifier: title
                block_view_type: large
        title:
            template: "NetgenBlockManagerBundle:block/view/title:default.html.twig"
            match:
                block_definition_identifier: title
        paragraph_small:
            template: "NetgenBlockManagerBundle:block/view/paragraph:small.html.twig"
            match:
                block_definition_identifier: paragraph
                block_view_type: small
        paragraph:
            template: "NetgenBlockManagerBundle:block/view/paragraph:default.html.twig"
            match:
                block_definition_identifier: paragraph
        # Fallback for block with `twig_block` definition identifier. Do not remove!
        twig_block:
            template: "NetgenBlockManagerBundle:block/view:twig_block.html.twig"
            match:
                block_definition_identifier: twig_block
    api_view:
        title:
            template: "NetgenBlockManagerBundle:api/block/view:title.html.twig"
            match:
                block_definition_identifier: title
                api_version: 1
        paragraph:
            template: "NetgenBlockManagerBundle:api/block/view:paragraph.html.twig"
            match:
                block_definition_identifier: paragraph
                api_version: 1
        block:
            template: "NetgenBlockManagerBundle:api/block:view.html.twig"
            match:
                api_version: 1
