default_view_templates:
    block_view:
        default: '@NetgenBlockManager/block/invalid_block.html.twig'
        api: '@NetgenBlockManager/api/block/block.html.twig'
    item_view:
        default: '@NetgenBlockManager/item/invalid_item.html.twig'
        api: '@NetgenBlockManager/api/item/invalid_item.html.twig'
    parameter_view:
        default: '@NetgenBlockManager/parameter/parameter.html.twig'
    placeholder_view:
        default: '@ngbm/placeholder/placeholder.html.twig'
    zone_view:
        default: '@ngbm/zone/zone.html.twig'
