default_view_templates:
    block_view:
        default: '@ngbm/block/block.html.twig'
        api: '@NetgenBlockManager/api/block/block.html.twig'
    item_view:
        default: '@NetgenBlockManager/item/invalid_item.html.twig'
        api: '@NetgenBlockManager/api/item/invalid_item.html.twig'
    parameter_view:
        default: '@NetgenBlockManager/parameter/parameter.html.twig'
    placeholder_view:
        default: '@NetgenBlockManager/placeholder/placeholder.html.twig'
