form_view:
    api_view:
        block\full_edit:
            template: "NetgenBlockManagerBundle:api/form/block:full.html.twig"
            match:
                form\type: Netgen\BlockManager\Block\Form\FullEditType
                api_version: 1
        block\content_edit:
            template: "NetgenBlockManagerBundle:api/form/block:content.html.twig"
            match:
                form\type: Netgen\BlockManager\Block\Form\ContentEditType
                api_version: 1
        block\design_edit:
            template: "NetgenBlockManagerBundle:api/form/block:design.html.twig"
            match:
                form\type: Netgen\BlockManager\Block\Form\DesignEditType
                api_version: 1
        query\full_edit\ezcontent_search:
            template: "NetgenBlockManagerBundle:api/form/query/full:ezcontent_search.html.twig"
            match:
                form\type: Netgen\BlockManager\Collection\Query\Form\FullEditType
                form\query\type: ezcontent_search
                api_version: 1
        query\full_edit:
            template: "NetgenBlockManagerBundle:api/form/query:full.html.twig"
            match:
                form\type: Netgen\BlockManager\Collection\Query\Form\FullEditType
                api_version: 1
