item_view:
    view:
        # Do not remove, fallback template for items which do not exist or are invalid
        item:
            template: "NetgenBlockManagerBundle:item/view:item.html.twig"
            match: ~
    api_view:
        # Do not remove, fallback template for items which do not exist or are invalid
        item:
            template: "NetgenBlockManagerBundle:api/item/view:item.html.twig"
            match: ~
