view:
    layout_view:
        default:
            invalid:
                template: "@NetgenBlockManager/layout/invalid_layout.html.twig"
                match:
                    layout\type: "null"
        api:
            invalid:
                template: "@NetgenBlockManager/api/layout/invalid_layout.html.twig"
                match:
                    layout\type: "null"
