layout_view:
    view:
        3_zones_a:
            template: "NetgenBlockManagerBundle:layout/view:3_zones_a.html.twig"
            match:
                layout\type: 3_zones_a
    api_view:
        3_zones_a:
            template: "NetgenBlockManagerBundle:api/layout/view:3_zones_a.html.twig"
            match:
                layout\type: 3_zones_a
                api_version: 1
