view:
    parameter_view:
        default:
            link:
                template: "NetgenBlockManagerBundle:parameter:link.html.twig"
                match:
                    parameter\type: link
