parameters:
    netgen_block_manager.view.renderer.twig.class: Netgen\BlockManager\View\Renderer\TwigViewRenderer

services:
    netgen_block_manager.view.renderer.twig:
        class: %netgen_block_manager.view.renderer.twig.class%
        arguments:
            - @twig

    netgen_block_manager.view.renderer:
        alias: netgen_block_manager.view.renderer.twig
