rule_condition_view:
    view:
        route_parameter:
            template: "NetgenBlockManagerAdminUIBundle:admin/rule_condition/view:route_parameter.html.twig"
            match:
                rule_condition\type: route_parameter
        rule_condition:
            template: "NetgenBlockManagerAdminUIBundle:admin/rule_condition:view.html.twig"
            match: ~
