rule_condition_view:
    view:
        siteaccess:
            template: "NetgenBlockManagerAdminUIBundle:admin/rule_condition/view:siteaccess.html.twig"
            match:
                condition\type: siteaccess
