rule_condition_view:
    view:
        ezsiteaccess:
            template: "NetgenBlockManagerAdminUIBundle:admin/rule_condition/view:ezsiteaccess.html.twig"
            match:
                condition\type: ezsiteaccess
