parameters:
    netgen_block_manager.view.template_resolver.block_view.class: Netgen\BlockManager\View\TemplateResolver\BlockViewTemplateResolver
    netgen_block_manager.view.template_resolver.layout_view.class: Netgen\BlockManager\View\TemplateResolver\LayoutViewTemplateResolver

services:
    netgen_block_manager.view.template_resolver.block_view:
        class: %netgen_block_manager.view.template_resolver.block_view.class%
        lazy: true
        arguments:
            - []
            - "@netgen_block_manager.configuration"
        tags:
            - { name: netgen_block_manager.view.template_resolver }

    netgen_block_manager.view.template_resolver.layout_view:
        class: %netgen_block_manager.view.template_resolver.layout_view.class%
        lazy: true
        arguments:
            - []
            - "@netgen_block_manager.configuration"
        tags:
            - { name: netgen_block_manager.view.template_resolver }
