parameters:
    netgen_block_manager.view.template_resolver.class: Netgen\BlockManager\View\TemplateResolver

services:
    netgen_block_manager.view.template_resolver.block:
        class: %netgen_block_manager.view.template_resolver.class%
        arguments:
            - []
            - %netgen_block_manager.block_view%
        tags:
            - { name: netgen_block_manager.view.template_resolver, type: 'Netgen\BlockManager\View\BlockViewInterface' }

    netgen_block_manager.view.template_resolver.layout:
        class: %netgen_block_manager.view.template_resolver.class%
        arguments:
            - []
            - %netgen_block_manager.layout_view%
        tags:
            - { name: netgen_block_manager.view.template_resolver, type: 'Netgen\BlockManager\View\LayoutViewInterface' }
