parameters:
    netgen_block_manager.view.template_resolver.block.class: Netgen\BlockManager\View\TemplateResolver\BlockViewTemplateResolver
    netgen_block_manager.view.template_resolver.layout.class: Netgen\BlockManager\View\TemplateResolver\LayoutViewTemplateResolver

services:
    netgen_block_manager.view.template_resolver.block:
        class: %netgen_block_manager.view.template_resolver.block.class%
        arguments:
            - %netgen_block_manager.default.block_templates%
        tags:
            - { name: netgen_block_manager.view.template_resolver, type: 'Netgen\BlockManager\View\BlockView' }

    netgen_block_manager.view.template_resolver.layout:
        class: %netgen_block_manager.view.template_resolver.layout.class%
        arguments:
            - %netgen_block_manager.default.layout_templates%
        tags:
            - { name: netgen_block_manager.view.template_resolver, type: 'Netgen\BlockManager\View\LayoutView' }
