parameters:
    netgen_block_manager.layout_resolver.condition_matcher.route_parameter.class: Netgen\BlockManager\LayoutResolver\ConditionMatcher\RouteParameter

services:
    netgen_block_manager.layout_resolver.condition_matcher.route_parameter:
        class: %netgen_block_manager.layout_resolver.condition_matcher.route_parameter.class%
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout_resolver.condition_matcher }
