parameters:
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.route.class: Netgen\BlockManager\LayoutResolver\RuleHandler\Doctrine\TargetHandler\Route
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.route_prefix.class: Netgen\BlockManager\LayoutResolver\RuleHandler\Doctrine\TargetHandler\RoutePrefix

services:
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.route:
        class: %netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.route.class%
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler }

    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.route_prefix:
        class: %netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.route_prefix.class%
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler }
