parameters:
    netgen_block_manager.view.matcher.api_version.class: Netgen\BlockManager\View\Matcher\APIVersion
    netgen_block_manager.view.matcher.form.type.class: Netgen\BlockManager\View\Matcher\Form\Type
    netgen_block_manager.view.matcher.form.block.definition.class: Netgen\BlockManager\View\Matcher\Form\Block\Definition
    netgen_block_manager.view.matcher.form.query.type.class: Netgen\BlockManager\View\Matcher\Form\Query\Type
    netgen_block_manager.view.matcher.layout.type.class: Netgen\BlockManager\View\Matcher\Layout\Type
    netgen_block_manager.view.matcher.block.definition.class: Netgen\BlockManager\View\Matcher\Block\Definition
    netgen_block_manager.view.matcher.block.view_type.class: Netgen\BlockManager\View\Matcher\Block\ViewType
    netgen_block_manager.view.matcher.item.view_type.class: Netgen\BlockManager\View\Matcher\Item\ViewType
    netgen_block_manager.view.matcher.item.value_type.class: Netgen\BlockManager\View\Matcher\Item\ValueType
    netgen_block_manager.view.matcher.rule_target.type.class: Netgen\BlockManager\View\Matcher\RuleTarget\Type
    netgen_block_manager.view.matcher.rule_condition.type.class: Netgen\BlockManager\View\Matcher\RuleCondition\Type

services:
    netgen_block_manager.view.matcher.api_version:
        class: "%netgen_block_manager.view.matcher.api_version.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: api_version }

    netgen_block_manager.view.matcher.form.type:
        class: "%netgen_block_manager.view.matcher.form.type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\type }

    netgen_block_manager.view.matcher.form.block.definition:
        class: "%netgen_block_manager.view.matcher.form.block.definition.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\block\definition }

    netgen_block_manager.view.matcher.form.query.type:
        class: "%netgen_block_manager.view.matcher.form.query.type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\query\type }

    netgen_block_manager.view.matcher.layout.type:
        class: "%netgen_block_manager.view.matcher.layout.type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: layout\type }

    netgen_block_manager.view.matcher.block.definition:
        class: "%netgen_block_manager.view.matcher.block.definition.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: block\definition }

    netgen_block_manager.view.matcher.block.view_type:
        class: "%netgen_block_manager.view.matcher.block.view_type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: block\view_type }

    netgen_block_manager.view.matcher.item.view_type:
        class: "%netgen_block_manager.view.matcher.item.view_type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: item\view_type }

    netgen_block_manager.view.matcher.item.value_type:
        class: "%netgen_block_manager.view.matcher.item.value_type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: item\value_type }

    netgen_block_manager.view.matcher.rule_target.type:
        class: "%netgen_block_manager.view.matcher.rule_target.type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: rule_target\type }

    netgen_block_manager.view.matcher.rule_condition.type:
        class: "%netgen_block_manager.view.matcher.rule_condition.type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: rule_condition\type }
