parameters:
    netgen_block_manager.view.matcher.layout.type.class: Netgen\BlockManager\View\Matcher\Layout\Type
    netgen_block_manager.view.matcher.api_version.class: Netgen\BlockManager\View\Matcher\APIVersion
    netgen_block_manager.view.matcher.block.definition_identifier.class: Netgen\BlockManager\View\Matcher\Block\DefinitionIdentifier
    netgen_block_manager.view.matcher.block.view_type.class: Netgen\BlockManager\View\Matcher\Block\ViewType
    netgen_block_manager.view.matcher.item.view_type.class: Netgen\BlockManager\View\Matcher\Item\ViewType
    netgen_block_manager.view.matcher.item.value_type.class: Netgen\BlockManager\View\Matcher\Item\ValueType

services:
    netgen_block_manager.view.matcher.api_version:
        class: "%netgen_block_manager.view.matcher.api_version.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: api_version }

    netgen_block_manager.view.matcher.layout.type:
        class: "%netgen_block_manager.view.matcher.layout.type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: layout_type }

    netgen_block_manager.view.matcher.block.definition_identifier:
        class: "%netgen_block_manager.view.matcher.block.definition_identifier.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: block_definition_identifier }

    netgen_block_manager.view.matcher.block.view_type:
        class: "%netgen_block_manager.view.matcher.block.view_type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: block_view_type }

    netgen_block_manager.view.matcher.item.view_type:
        class: "%netgen_block_manager.view.matcher.item.view_type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: item_view_type }

    netgen_block_manager.view.matcher.item.value_type:
        class: "%netgen_block_manager.view.matcher.item.value_type.class%"
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: item_value_type }
