services:
    netgen_block_manager.view.provider.parameter:
        class: Netgen\BlockManager\View\Provider\ParameterViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }

    netgen_block_manager.view.provider.block:
        class: Netgen\BlockManager\View\Provider\BlockViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }

    netgen_block_manager.view.provider.item:
        class: Netgen\BlockManager\View\Provider\ItemViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }

    netgen_block_manager.view.provider.layout:
        class: Netgen\BlockManager\View\Provider\LayoutViewProvider
        tags:
            - { name: netgen_block_manager.view.provider, priority: 10 }

    netgen_block_manager.view.provider.form:
        class: Netgen\BlockManager\View\Provider\FormViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }

    netgen_block_manager.view.provider.rule:
        class: Netgen\BlockManager\View\Provider\RuleViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }

    netgen_block_manager.view.provider.rule_target:
        class: Netgen\BlockManager\View\Provider\RuleTargetViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }

    netgen_block_manager.view.provider.rule_condition:
        class: Netgen\BlockManager\View\Provider\RuleConditionViewProvider
        tags:
            - { name: netgen_block_manager.view.provider }
