parameters:
    netgen_block_manager.view.builder.class: Netgen\BlockManager\View\ViewBuilder
    netgen_block_manager.view.renderer.class: Netgen\BlockManager\View\Renderer
    netgen_block_manager.view.template_resolver.class: Netgen\BlockManager\View\TemplateResolver

services:
    netgen_block_manager.view.builder:
        class: "%netgen_block_manager.view.builder.class%"
        arguments:
            - "@netgen_block_manager.view.template_resolver"
            - "@event_dispatcher"
            - []

    netgen_block_manager.view.renderer:
        class: "%netgen_block_manager.view.renderer.class%"
        lazy: true
        arguments:
            - "@netgen_block_manager.view.builder"
            - "@twig"

    netgen_block_manager.view.template_resolver:
        class: "%netgen_block_manager.view.template_resolver.class%"
        lazy: true
        arguments:
            - []
            -
                layout_view: "@=service('netgen_block_manager.configuration').getParameter('layout_view')"
                block_view: "@=service('netgen_block_manager.configuration').getParameter('block_view')"
                item_view: "@=service('netgen_block_manager.configuration').getParameter('item_view')"
                form_view: "@=service('netgen_block_manager.configuration').getParameter('form_view')"
                rule_target_view: "@=service('netgen_block_manager.configuration').getParameter('rule_target_view')"
                rule_condition_view: "@=service('netgen_block_manager.configuration').getParameter('rule_condition_view')"
