services:
    netgen_block_manager.view.builder:
        class: Netgen\BlockManager\View\ViewBuilder
        arguments:
            - "@netgen_block_manager.view.template_resolver"
            - "@event_dispatcher"
            - []

    netgen_block_manager.view.renderer:
        class: Netgen\BlockManager\View\Renderer
        lazy: true
        arguments:
            - "@netgen_block_manager.view.builder"
            - "@twig"

    netgen_block_manager.view.template_resolver:
        class: Netgen\BlockManager\View\TemplateResolver
        lazy: true
        arguments:
            - []
            - "@=service('netgen_block_manager.configuration').getParameter('view')"
