services:
    netgen_block_manager.view.view_renderer:
        class: Netgen\BlockManager\View\ViewRenderer
        arguments:
            - "@event_dispatcher"
            - "@twig"

    netgen_block_manager.view.view_builder:
        class: Netgen\BlockManager\View\ViewBuilder
        arguments:
            - "@netgen_block_manager.view.template_resolver"
            - "@event_dispatcher"
            - []

    netgen_block_manager.view.renderer:
        alias: netgen_block_manager.view.renderer.default

    netgen_block_manager.view.renderer.default:
        class: Netgen\BlockManager\View\Renderer
        lazy: true
        arguments:
            - "@netgen_block_manager.view.view_builder"
            - "@netgen_block_manager.view.view_renderer"

    netgen_block_manager.view.renderer.fragment:
        class: Netgen\BlockManager\View\FragmentRenderer
        arguments:
            - "@netgen_block_manager.view.view_builder"
            - "@netgen_block_manager.view.view_renderer"
            - "@fragment.handler"
            - []

    netgen_block_manager.view.renderer.fragment.block_view_renderer:
        class: Netgen\BlockManager\View\Fragment\BlockViewRenderer
        arguments:
            - "@netgen_block_manager.http_cache.block.cacheable_resolver"
            - "%netgen_block_manager.controller.block_controller%"
        tags:
            - { name: netgen_block_manager.view.fragment_view_renderer }

    netgen_block_manager.view.template_resolver:
        class: Netgen\BlockManager\View\TemplateResolver
        lazy: true
        arguments:
            - []
            - "@=service('netgen_block_manager.configuration').getParameter('view')"
