parameters:
    netgen_block_manager.controller.admin.layout_resolver.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\Admin\LayoutResolverController
    netgen_block_manager.controller.app.index.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\App\IndexController
    netgen_block_manager.controller.app.block.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\App\BlockController

services:
    netgen_block_manager.controller.admin.layout_resolver:
        class: "%netgen_block_manager.controller.admin.layout_resolver.class%"
        parent: netgen_block_manager.controller.base

    netgen_block_manager.controller.app.index:
        class: "%netgen_block_manager.controller.app.index.class%"
        parent: netgen_block_manager.controller.base

    netgen_block_manager.controller.app.block:
        class: "%netgen_block_manager.controller.app.block.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.collection"
            - "@netgen_block_manager.collection.registry.query_type"
