parameters:
    netgen_block_manager.controller.admin.layout_resolver.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\Admin\LayoutResolverController

    netgen_block_manager.controller.app.index.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\App\IndexController
    netgen_block_manager.controller.app.layout.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\App\LayoutController
    netgen_block_manager.controller.app.block.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\App\BlockController
    netgen_block_manager.controller.app.collection.class: Netgen\Bundle\BlockManagerAdminUIBundle\Controller\App\CollectionController

services:
    netgen_block_manager.controller.admin.layout_resolver:
        class: "%netgen_block_manager.controller.admin.layout_resolver.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.layout.resolver.registry.target_type"
            - "@netgen_block_manager.layout.resolver.registry.condition_type"

    netgen_block_manager.controller.app.index:
        class: "%netgen_block_manager.controller.app.index.class%"
        parent: netgen_block_manager.controller.base

    netgen_block_manager.controller.app.layout:
        class: "%netgen_block_manager.controller.app.layout.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.app.block:
        class: "%netgen_block_manager.controller.app.block.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.api.service.collection"
            - "@netgen_block_manager.collection.registry.query_type"

    netgen_block_manager.controller.app.collection:
        class: "%netgen_block_manager.controller.app.collection.class%"
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.collection"
