services:
    netgen_block_manager.debug.data_collector:
        class: Netgen\Bundle\BlockManagerDebugBundle\DataCollector\BlockManagerDataCollector
        arguments:
            - "@netgen_block_manager.templating.global_variable"
            - "@netgen_block_manager.api.repository"
        tags:
            - { name: data_collector, template: 'NetgenBlockManagerDebugBundle:data_collector:ngbm.html.twig', id: ngbm }

    netgen_block_manager.debug.data_collector.event_listener.block_view:
        class: Netgen\Bundle\BlockManagerDebugBundle\DataCollector\EventListener\BlockViewListener
        arguments:
            - "@netgen_block_manager.debug.data_collector"
        tags:
            - { name: kernel.event_subscriber }
