netgen_block_manager_api_v1_config:
    resource: "api_v1/config.yml"

netgen_block_manager_api_v1_blocks:
    resource: "api_v1/blocks.yml"

netgen_block_manager_api_v1_collections:
    resource: "api_v1/block_collections.yml"

netgen_block_manager_api_v1_layouts:
    resource: "api_v1/layouts.yml"
