netgen_block_manager_api_v1_load_block:
    path: /blocks/{blockId}
    defaults:
        _controller: netgen_block_manager.controller.api.block:view

netgen_block_manager_api_v1_edit_block:
    path: /blocks/{blockId}/edit
    defaults:
        _controller: netgen_block_manager.controller.api.block:edit

netgen_block_manager_api_v1_load_layout:
    path: /layouts/{layoutId}
    defaults:
        _controller: netgen_block_manager.controller.api.layout:view
