services:
    netgen_block_manager.controller.admin.layout_resolver:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolverController
        public: true
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.layout.resolver.registry.target_type"
            - "@netgen_block_manager.layout.resolver.registry.condition_type"
            - "@netgen_block_manager.controller.admin.layout_resolver.validator"

    netgen_block_manager.controller.admin.layouts:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutsController
        public: true
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.http_cache.client"
            - "@netgen_block_manager.transfer.serializer"

    netgen_block_manager.controller.admin.shared_layouts:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\SharedLayoutsController
        public: true
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.http_cache.client"

    netgen_block_manager.controller.admin.layout_resolver.validator:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Validator\LayoutResolverValidator
        public: false
        calls:
            - [setValidator, ["@validator"]]

    # App controllers

    netgen_block_manager.controller.app.base:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Controller
        public: false
        abstract: true
        parent: netgen_block_manager.controller.base

    ## Index controller

    netgen_block_manager.controller.app.index:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Index
        public: true
        parent: netgen_block_manager.controller.app.base

    ## Layout controllers

    netgen_block_manager.controller.app.layout.create_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\CreateForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.app.layout.edit_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\EditForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.app.layout.set_main_locale_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\SetMainLocaleForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.app.layout.add_locale_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\AddLocaleForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.app.layout.remove_locale_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\RemoveLocaleForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    ## Block controllers

    netgen_block_manager.controller.app.block.edit:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\Edit
        public: true
        parent: netgen_block_manager.controller.app.base

    netgen_block_manager.controller.app.block.edit_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\EditForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.block"

    netgen_block_manager.controller.app.block.edit_config_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\EditConfigForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.block"

    netgen_block_manager.controller.app.block.configure_translation_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\ConfigureTranslationForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.block"

    ## Collection controllers

    netgen_block_manager.controller.app.collection.edit_collection_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Collection\EditCollectionForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.collection"

    netgen_block_manager.controller.app.collection.edit_item_config_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Collection\EditItemConfigForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.collection"

    netgen_block_manager.controller.app.collection.edit_query_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Collection\EditQueryForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.collection"
