services:
    netgen_block_manager.controller.admin.layout_resolver:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolverController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.layout.resolver.registry.target_type"
            - "@netgen_block_manager.layout.resolver.registry.condition_type"
            - "@netgen_block_manager.controller.admin.layout_resolver.validator"

    netgen_block_manager.controller.admin.layouts:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutsController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.http_cache.client"

    netgen_block_manager.controller.admin.shared_layouts:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\SharedLayoutsController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.admin.layout_resolver.validator:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Validator\LayoutResolverValidator
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.controller.app.index:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\IndexController
        parent: netgen_block_manager.controller.base

    netgen_block_manager.controller.app.layout:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\LayoutController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.app.block:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\BlockController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.block"

    netgen_block_manager.controller.app.collection:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\CollectionController
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_block_manager.api.service.collection"
