parameters:
    netgen_block_manager.event_listener.layout_view.rule_count.class: Netgen\Bundle\BlockManagerAdminBundle\EventListener\LayoutView\RuleCountListener
    netgen_block_manager.event_listener.admin_authentication_exception.class: Netgen\Bundle\BlockManagerAdminBundle\EventListener\AdminAuthenticationExceptionListener
    netgen_block_manager.event_listener.set_is_admin_request.class: Netgen\Bundle\BlockManagerAdminBundle\EventListener\SetIsAdminRequestListener
    netgen_block_manager.event_listener.admin_csrf_validation_listener.class: Netgen\Bundle\BlockManagerAdminBundle\EventListener\CsrfValidation\AdminCsrfValidationListener

services:
    netgen_block_manager.event_listener.layout_view.rule_count:
        class: "%netgen_block_manager.event_listener.layout_view.rule_count.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.admin_authentication_exception:
        class: "%netgen_block_manager.event_listener.admin_authentication_exception.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.set_is_admin_request:
        class: "%netgen_block_manager.event_listener.set_is_admin_request.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.admin_csrf_validation_listener:
        class: "%netgen_block_manager.event_listener.admin_csrf_validation_listener.class%"
        arguments:
            - "@security.csrf.token_manager"
            - "%netgen_block_manager.admin.csrf_token_id%"
        tags:
            - { name: kernel.event_subscriber }
