block_types:
    test_grid:
        name: 'Test grid'
        definition_identifier: list
        defaults:
            view_type: test_grid
            item_view_type: test_item

block_type_groups:
    test_blocks:
        name: 'Test blocks'
        block_types: [test_grid, list_without_value_types]
