layout_types:
    4_zones_a:
        name: '4 zones A'
        zones:
            top:
                name: 'Top'
                allowed_block_definitions: [title]
            left:
                name: 'Left'
            right:
                name: 'Right'
            bottom:
                name: 'Bottom'

    4_zones_b:
        name: '4 zones B'
        zones:
            top:
                name: 'Top'
            left:
                name: 'Left'
            right:
                name: 'Right'
            bottom:
                name: 'Bottom'
