parameters:
    netgen_block_manager.persistence.doctrine.handler.class: Netgen\BlockManager\Core\Persistence\Doctrine\Handler
    netgen_block_manager.persistence.doctrine.connection_helper.class: Netgen\BlockManager\Core\Persistence\Doctrine\Connection\Helper

    netgen_block_manager.api.service.mapper.class: Netgen\BlockManager\Core\Service\Mapper

    netgen_block_manager.persistence.doctrine.layout.mapper.class: Netgen\BlockManager\Core\Persistence\Doctrine\Layout\Mapper
    netgen_block_manager.persistence.doctrine.layout.handler.class: Netgen\BlockManager\Core\Persistence\Doctrine\Layout\Handler
    netgen_block_manager.api.service.layout.core.class: Netgen\BlockManager\Core\Service\LayoutService

    netgen_block_manager.api.service.block.core.class: Netgen\BlockManager\Core\Service\BlockService

services:
    netgen_block_manager.persistence.doctrine.handler:
        class: "%netgen_block_manager.persistence.doctrine.handler.class%"
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.layout.handler"

    netgen_block_manager.api.service.mapper:
        class: "%netgen_block_manager.api.service.mapper.class%"
        arguments:
            - "@netgen_block_manager.persistence.handler"

    # Layout related APIs

    netgen_block_manager.persistence.doctrine.connection_helper:
        class: "%netgen_block_manager.persistence.doctrine.connection_helper.class%"
        arguments:
            - "@database_connection"

    netgen_block_manager.persistence.doctrine.layout.mapper:
        class: "%netgen_block_manager.persistence.doctrine.layout.mapper.class%"

    netgen_block_manager.persistence.doctrine.layout.handler:
        class: "%netgen_block_manager.persistence.doctrine.layout.handler.class%"
        arguments:
            - "@database_connection"
            - "@netgen_block_manager.persistence.doctrine.connection_helper"
            - "@netgen_block_manager.persistence.doctrine.layout.mapper"

    netgen_block_manager.api.service.layout.core:
        class: "%netgen_block_manager.api.service.layout.core.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout.validator"
            - "@netgen_block_manager.persistence.handler"
            - "@netgen_block_manager.api.service.mapper"

    # Block related APIs

    netgen_block_manager.api.service.block.core:
        class: "%netgen_block_manager.api.service.block.core.class%"
        arguments:
            - "@netgen_block_manager.api.service.block.validator"
            - "@netgen_block_manager.persistence.handler"
            - "@netgen_block_manager.api.service.mapper"

    # Service aliases

    netgen_block_manager.api.service.layout:
        alias: netgen_block_manager.api.service.layout.core

    netgen_block_manager.api.service.block:
        alias: netgen_block_manager.api.service.block.core

    netgen_block_manager.persistence.handler:
        alias: netgen_block_manager.persistence.doctrine.handler
