block_definitions:
    title:
        forms:
            design:
                type: ~
                parameters: [tag]
            content:
                type: ~
                parameters: [title]
        view_types:
            default:
                name: 'Default'
            large:
                name: 'Large'
    paragraph:
        forms:
            full:
                type: ~
        view_types:
            default:
                name: 'Default'
            small:
                name: 'Small'
    twig_block:
        forms:
            full:
                type: ~
        view_types:
            default:
                name: 'Default'
