parameters:
    netgen_block_manager.default.blocks:
        title:
            name: 'Title'
            view_types: ['default', 'small']
        paragraph:
            name: 'Paragraph'
            view_types: ['default', 'small']

    netgen_block_manager.default.block_groups:
        simple_blocks:
            name: 'Simple blocks'
            blocks: [paragraph, title]
