block_definitions:
    title:
        view_types:
            title:
                name: 'Title'

    text:
        view_types:
            text:
                name: 'Text'

    markdown:
        view_types:
            markdown:
                name: 'Markdown'

    rich_text:
        view_types:
            rich_text:
                name: 'Rich text'

    html_snippet:
        view_types:
            html_snippet:
                name: 'HTML snippet'

    full_view:
        view_types:
            full_view:
                name: 'Full view'

    twig_block:
        view_types:
            twig_block:
                name: 'Twig block'

    external_video:
        view_types:
            external_video:
                name: 'External video'

    map:
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            map:
                name: 'Map'

    list:
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            list:
                name: 'List'
                valid_parameters: [css_class, css_id, set_container]
            grid:
                name: 'Grid'

    gallery:
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            slider:
                name: 'Slider'
                valid_parameters:
                    - next_and_previous
                    - show_pagination
                    - infinite_loop
                    - transition
                    - autoplay
                    - aspect_ratio
                    - css_class
                    - css_id
                    - set_container
            thumb_gallery:
                name: 'Thumb gallery'
                valid_parameters:
                    - next_and_previous
                    - aspect_ratio
                    - show_details
                    - css_class
                    - css_id
                    - set_container
            grid_gallery:
                name: 'Grid gallery'
                valid_parameters:
                    - aspect_ratio
                    - number_of_thumbnails
                    - enable_lightbox
                    - css_class
                    - css_id
                    - set_container
            sushi_bar:
                name: 'Sushi bar'
                valid_parameters:
                    - next_and_previous
                    - show_pagination
                    - infinite_loop
                    - autoplay
                    - aspect_ratio
                    - number_of_thumbnails
                    - css_class
                    - css_id
                    - set_container
