block_types:
    title:
        name: 'Title'
        definition_identifier: title
        defaults:
            view_type: title
            item_view_type: standard
            parameters:
                tag: h1
                title: 'Title'

    text:
        name: 'Text'
        definition_identifier: paragraph
        defaults:
            view_type: text
            item_view_type: standard
            parameters:
                content: 'Text'

    external_video:
        name: 'External video'
        definition_identifier: external_video
        defaults:
            view_type: external_video
            item_view_type: standard
            parameters:
                service: youtube
                video_id: ' '

    map:
        name: 'Map'
        definition_identifier: map
        defaults:
            view_type: map
            item_view_type: standard
            parameters:
                latitude: 0
                longitude: 0
                zoom: 5
                map_type: roadmap
                show_marker: true

    html_snippet:
        name: 'HTML snippet'
        definition_identifier: html_snippet
        defaults:
            view_type: html_snippet
            item_view_type: standard

    content:
        name: 'Content'
        definition_identifier: twig_block
        defaults:
            view_type: twig_block
            item_view_type: standard
            parameters:
                block_name: content

    list:
        name: 'List'
        definition_identifier: list
        defaults:
            view_type: list
            item_view_type: standard
            parameters:
                number_of_columns: 1

    grid:
        name: 'Grid'
        definition_identifier: list
        defaults:
            view_type: grid
            item_view_type: standard
            parameters:
                number_of_columns: 3

    slider:
        name: 'Slider'
        definition_identifier: gallery
        defaults:
            view_type: slider
            item_view_type: standard
            parameters:
                transition: default
                aspect_ratio: 16_9
                autoplay_time: 1
                number_of_thumbnails: 1

    thumb_gallery:
        name: 'Thumb gallery'
        definition_identifier: gallery
        defaults:
            view_type: thumb_gallery
            item_view_type: standard
            parameters:
                transition: default
                aspect_ratio: 16_9
                autoplay_time: 1
                number_of_thumbnails: 1

    grid_gallery:
        name: 'Grid gallery'
        definition_identifier: gallery
        defaults:
            view_type: grid_gallery
            item_view_type: standard
            parameters:
                transition: default
                aspect_ratio: 16_9
                autoplay_time: 1
                number_of_thumbnails: 1

    sushi_bar:
        name: 'Sushi bar'
        definition_identifier: gallery
        defaults:
            view_type: sushi_bar
            item_view_type: standard
            parameters:
                transition: default
                aspect_ratio: 16_9
                autoplay_time: 1
                number_of_thumbnails: 1
