block_definitions:
    title:
        forms:
            full: ~
        view_types:
            default:
                name: 'Default'
            large:
                name: 'Large'
    paragraph:
        forms:
            full: ~
        view_types:
            default:
                name: 'Default'
            small:
                name: 'Small'
