blocks:
    title:
        forms:
            inline: block_inline_edit_title
        view_types:
            default:
                name: Default
            large:
                name: Large
    paragraph:
        forms:
            inline: block_inline_edit_paragraph
        view_types:
            default:
                name: Default
            small:
                name: Small
