block_types:
#    container:
#        name: 'Container'
#        defaults:
#            view_type: default
#            definition_identifier: container
    title:
        name: 'Title'
        definition_identifier: title
        defaults:
            view_type: default
            parameters:
                tag: h1
                title: 'My cool title'
    title_with_h3:
        name: 'Title with h3'
        definition_identifier: title
        defaults:
            view_type: large
#            sub_blocks:
#                left:
#                    type: container
#                right:
#                    type: container
#                top:
#                    type: container
#                bottom:
#                    type: title
#                    defaults:
#                        view_type: default
#                        parameters:
#                            title: 'Sub title 1'
            parameters:
                title: 'Title with h3'
                tag: h3
    paragraph:
       name: 'Paragraph'
       definition_identifier: paragraph
       defaults:
           view_type: default
           parameters:
               content: 'My cool paragraph'
