block_type_groups:
    typography:
        name: 'Typography'
        block_types: [title, text, rich_text]
    basic:
        name: 'Basic'
        block_types: [external_video, map, html_snippet]
    listing:
        name: 'Listing'
        block_types: [list, grid]
    gallery:
        name: 'Gallery'
        block_types: [slider, thumb_gallery, grid_gallery, sushi_bar]
    content:
        name: 'Content'
        block_types: [content]
