blocks:
    title:
        forms: ~
        view_types:
            default:
                name: Default
            large:
                name: Large
    paragraph:
        forms: ~
        view_types:
            default:
                name: Default
            small:
                name: Small
