parameters:
    netgen_block_manager.block_definition.form.block_edit.class: Netgen\BlockManager\BlockDefinition\Form\BlockEditType
    netgen_block_manager.block_definition.form.block_inline_edit_title.class: Netgen\BlockManager\BlockDefinition\Form\TitleInlineType
    netgen_block_manager.block_definition.form.block_inline_edit_paragraph.class: Netgen\BlockManager\BlockDefinition\Form\ParagraphInlineType

services:
    netgen_block_manager.block_definition.form.block_edit:
        class: "%netgen_block_manager.block_definition.form.block_edit.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
            - "@netgen_block_manager.block_definition.registry"
            - "@netgen_block_manager.configuration"
        tags:
            - { name: form.type, alias: block_edit }

    netgen_block_manager.block_definition.form.block_inline_edit_title:
        class: "%netgen_block_manager.block_definition.form.block_inline_edit_title.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
            - "@netgen_block_manager.block_definition.registry"
            - "@netgen_block_manager.configuration"
        tags:
            - { name: form.type, alias: block_inline_edit_title }

    netgen_block_manager.block_definition.form.block_inline_edit_paragraph:
        class: "%netgen_block_manager.block_definition.form.block_inline_edit_paragraph.class%"
        arguments:
            - "@netgen_block_manager.parameters.form_mapper"
            - "@netgen_block_manager.block_definition.registry"
            - "@netgen_block_manager.configuration"
        tags:
            - { name: form.type, alias: block_inline_edit_paragraph }
