block_type_groups:
    basic:
        name: 'Basic'
        block_types: [title, text, rich_text, external_video, map, html_snippet]
    listing:
        name: 'Listing'
        block_types: [list, grid]
    gallery:
        name: 'Gallery'
        block_types: [slider, thumb_gallery, grid_gallery, sushi_bar]
    placeholders:
        name: 'Placeholders'
        block_types: [content, twig_block]
