blocks:
    title:
        forms:
            inline: title_inline
        view_types:
            default:
                name: Default
            large:
                name: Large
    paragraph:
        forms:
            inline: paragraph_inline
        view_types:
            default:
                name: Default
            small:
                name: Small
