block_types:
    title:
        type_name: 'Title'
        defaults:
            view_type: default
            definition_identifier: title
            parameters:
                tag: h1
                title: 'My cool title'
    title_with_h3:
        type_name: 'Title with h3'
        defaults:
            view_type: large
            definition_identifier: title
            parameters:
                tag: h3
