block_definitions:
    title:
        forms:
            full:
                type: ~
        view_types:
            title:
                name: 'Title'

    text:
        forms:
            full:
                type: ~
        view_types:
            text:
                name: 'Text'

    rich_text:
        forms:
            full:
                type: ~
        view_types:
            rich_text:
                name: 'Rich text'

    html_snippet:
        forms:
            full:
                type: ~
        view_types:
            html_snippet:
                name: 'HTML snippet'

    content:
        forms:
            full:
                type: ~
        view_types:
            content:
                name: 'Content'

    twig_block:
        forms:
            full:
                type: ~
        view_types:
            twig_block:
                name: 'Twig block'

    external_video:
        forms:
            full:
                type: ~
        view_types:
            external_video:
                name: 'External video'

    map:
        forms:
            content:
                type: ~
                parameters: [latitude, longitude]
            design:
                type: ~
                parameters: [zoom, map_type, show_marker, css_class, css_id]
        view_types:
            map:
                name: 'Map'

    list:
        forms:
            content:
                type: ~
            design:
                type: ~
                parameters: [number_of_columns, css_class, css_id]
        view_types:
            list:
                name: 'List'
            grid:
                name: 'Grid'

    gallery:
        forms:
            content:
                type: ~
            design:
                type: ~
                parameters:
                    - next_and_previous
                    - show_pagination
                    - infinite_loop
                    - transition
                    - autoplay
                    - aspect_ratio
                    - show_details
                    - number_of_thumbnails
                    - enable_lightbox
                    - css_class
                    - css_id
        view_types:
            slider:
                name: 'Slider'
            thumb_gallery:
                name: 'Thumb gallery'
            grid_gallery:
                name: 'Grid gallery'
            sushi_bar:
                name: 'Sushi bar'
