block_definitions:
    title:
        name: 'Title'
        view_types:
            title:
                name: 'Title'

    text:
        name: 'Text'
        view_types:
            text:
                name: 'Text'

    button:
        name: 'Button / Link'
        view_types:
            button:
                name: 'Button / Link'

    markdown:
        name: 'Markdown'
        enabled: false
        view_types:
            markdown:
                name: 'Markdown'

    rich_text:
        name: 'Rich text'
        view_types:
            rich_text:
                name: 'Rich text'

    html_snippet:
        name: 'HTML snippet'
        view_types:
            html_snippet:
                name: 'HTML snippet'

    full_view:
        name: 'Full view'
        view_types:
            full_view:
                name: 'Full view'

    twig_block:
        name: 'Twig block'
        view_types:
            twig_block:
                name: 'Twig block'

    external_video:
        name: 'External video'
        view_types:
            external_video:
                name: 'External video'

    map:
        name: 'Map'
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            map:
                name: 'Map'

    list:
        name: 'List'
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            list:
                name: 'List'
                valid_parameters: [css_class, css_id, set_container]
            grid:
                name: 'Grid'

    gallery:
        name: 'Gallery'
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            slider:
                name: 'Slider'
                valid_parameters:
                    - next_and_previous
                    - show_pagination
                    - infinite_loop
                    - transition
                    - autoplay
                    - aspect_ratio
                    - css_class
                    - css_id
                    - set_container
            thumb_gallery:
                name: 'Thumb gallery'
                valid_parameters:
                    - next_and_previous
                    - aspect_ratio
                    - show_details
                    - css_class
                    - css_id
                    - set_container
            grid_gallery:
                name: 'Grid gallery'
                valid_parameters:
                    - aspect_ratio
                    - number_of_thumbnails
                    - enable_lightbox
                    - css_class
                    - css_id
                    - set_container
            sushi_bar:
                name: 'Sushi bar'
                valid_parameters:
                    - next_and_previous
                    - show_pagination
                    - infinite_loop
                    - autoplay
                    - aspect_ratio
                    - number_of_thumbnails
                    - css_class
                    - css_id
                    - set_container

    dynamic_container:
        name: 'Dynamic container'
        view_types:
            dynamic_container:
                name: 'Dynamic container'

    div_container:
        name: '<div> container'
        view_types:
            div_container:
                name: '<div> container'

    two_columns_container:
        name: 'Two columns container'
        view_types:
            50_50:
                name: '50:50'
            33_66:
                name: '33:66'
            66_33:
                name: '66_33'
