block_types:
    title:
        name: 'Title'
        definition_identifier: title
        defaults:
            view_type: default
            item_view_type: standard
            parameters:
                tag: h1
                title: 'Title'

    text:
       name: 'Text'
       definition_identifier: paragraph
       defaults:
           view_type: default
           item_view_type: standard
           parameters:
               content: 'Text'

    html_snippet:
       name: 'HTML snippet'
       definition_identifier: html_snippet
       defaults:
           view_type: default
           item_view_type: standard

    content_block:
       name: 'Content block'
       definition_identifier: twig_block
       defaults:
           view_type: default
           item_view_type: standard
           parameters:
               block_name: 'content'
