block_types:
    title:
        name: 'Title'
        definition_identifier: title

    text:
        name: 'Text'
        definition_identifier: text

    link:
        name: 'Link'
        definition_identifier: link

    markdown:
        name: 'Markdown'
        definition_identifier: markdown
        enabled: false

    rich_text:
        name: 'Rich text'
        definition_identifier: rich_text

    external_video:
        name: 'External video'
        definition_identifier: external_video

    map:
        name: 'Map'
        definition_identifier: map

    html_snippet:
        name: 'HTML snippet'
        definition_identifier: html_snippet

    full_view:
        name: 'Full view'
        definition_identifier: full_view

    twig_block:
        name: 'Twig block'
        definition_identifier: twig_block

    list:
        name: 'List'
        definition_identifier: list

    grid:
        name: 'Grid'
        definition_identifier: list
        defaults:
            view_type: grid
            parameters:
                number_of_columns: 3

    slider:
        name: 'Slider'
        definition_identifier: gallery

    thumb_gallery:
        name: 'Thumb gallery'
        definition_identifier: gallery
        defaults:
            view_type: thumb_gallery

    grid_gallery:
        name: 'Grid gallery'
        definition_identifier: gallery
        defaults:
            view_type: grid_gallery

    sushi_bar:
        name: 'Sushi bar'
        definition_identifier: gallery
        defaults:
            view_type: sushi_bar
