block_definitions:
    title:
        forms:
            content:
                type: ~
                parameters: [title]
            design:
                type: ~
                parameters: [tag, css_class, css_id]
        view_types:
            default:
                name: 'Default'
                item_view_types:
                    standard:
                        name: 'Standard'
            small:
                name: 'Small'
                item_view_types:
                    standard:
                        name: 'Standard'
    paragraph:
        forms:
            full:
                type: ~
        view_types:
            default:
                name: 'Default'
                item_view_types:
                    standard:
                        name: 'Standard'
            large:
                name: 'Large'
                item_view_types:
                    standard:
                        name: 'Standard'
    html_snippet:
        forms:
            full:
                type: ~
        view_types:
            default:
                name: 'Default'
                item_view_types:
                    standard:
                        name: 'Standard'

    twig_block:
        forms:
            full:
                type: ~
        view_types:
            default:
                name: 'Default'
                item_view_types:
                    standard:
                        name: 'Standard'

    map:
        forms:
            content:
                type: ~
                parameters: [latitude, longitude, zoom, map_type, show_marker]
            design:
                type: ~
                parameters: [css_class, css_id]
        view_types:
            default:
                name: 'Default'
                item_view_types:
                    standard:
                        name: 'Standard'

    list:
        forms:
            content:
                type: ~
                parameters: [number_of_columns]
            design:
                type: ~
                parameters: [css_class, css_id]
        view_types:
            list:
                name: 'List'
                item_view_types:
                    standard:
                        name: 'Standard'
            grid:
                name: 'Grid'
                item_view_types:
                    standard:
                        name: 'Standard'

    gallery:
        forms:
            content:
                type: ~
                parameters: [number_of_thumbnails]
            design:
                type: ~
                parameters:
                    - next_and_previous
                    - show_pagination
                    - infinite_loop
                    - transition
                    - autoplay
                    - aspect_ratio
                    - show_details
                    - enable_lightbox
                    - css_class
                    - css_id
        view_types:
            slider:
                name: 'Slider'
                item_view_types:
                    standard:
                        name: 'Standard'
            thumb_gallery:
                name: 'Thumb gallery'
                item_view_types:
                    standard:
                        name: 'Standard'
            grid_gallery:
                name: 'Grid gallery'
                item_view_types:
                    standard:
                        name: 'Standard'
            sushi_bar:
                name: 'Sushi bar'
                item_view_types:
                    standard:
                        name: 'Standard'
