container_types:
    two_columns:
        enabled: false

    two_columns_50_50:
        name: 'Two columns (50:50)'
        definition_identifier: two_columns
        defaults:
            view_type: 50_50

    two_columns_33_66:
        name: 'Two columns (33:66)'
        definition_identifier: two_columns
        defaults:
            view_type: 33_66

    two_columns_66_33:
        name: 'Two columns (66_33)'
        definition_identifier: two_columns
        defaults:
            view_type: 66_33
