parameters:
    netgen_block_manager.controller.api.base.class: Netgen\Bundle\BlockManagerBundle\Controller\API\Controller
    netgen_block_manager.controller.api.layout.class: Netgen\Bundle\BlockManagerBundle\Controller\API\LayoutController
    netgen_block_manager.controller.api.block.class: Netgen\Bundle\BlockManagerBundle\Controller\API\BlockController

services:
    netgen_block_manager.controller.api.base:
        class: %netgen_block_manager.controller.api.base.class%
        abstract: true
        calls:
            - [setContainer, [@service_container]]

    netgen_block_manager.controller.api.layout:
        class: %netgen_block_manager.controller.api.layout.class%
        parent: netgen_block_manager.controller.api.base

    netgen_block_manager.controller.api.block:
        class: %netgen_block_manager.controller.api.block.class%
        parent: netgen_block_manager.controller.api.base
