parameters:
    netgen_block_manager.route_prefix: /bm
    netgen_block_manager.block_view.dynamic_parameters_contexts: ['default']
    netgen_block_manager.block_view.collection_results_contexts: ['default', 'api']
    netgen_block_manager.api.csrf_token_id: ngbm_api
