parameters:
    netgen_block_manager.route_prefix: /bm
    netgen_block_manager.block_view.dynamic_parameters_contexts: ['view']
    netgen_block_manager.block_view.collection_results_contexts: ['view']
