parameters:
    netgen_block_manager.event_listener.exception_conversion.class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionConversionListener
    netgen_block_manager.event_listener.exception_serializer.class: Netgen\Bundle\BlockManagerBundle\EventListener\ExceptionSerializerListener
    netgen_block_manager.event_listener.set_is_api_request.class: Netgen\Bundle\BlockManagerBundle\EventListener\SetIsApiRequestListener
    netgen_block_manager.event_listener.layout_resolver.class: Netgen\Bundle\BlockManagerBundle\EventListener\LayoutResolverListener

services:
    netgen_block_manager.event_listener.exception_conversion:
        class: %netgen_block_manager.event_listener.exception_conversion.class%
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.exception_serializer:
        class: %netgen_block_manager.event_listener.exception_serializer.class%
        arguments:
            - @serializer
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.set_is_api_request:
        class: %netgen_block_manager.event_listener.set_is_api_request.class%
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.layout_resolver:
        class: %netgen_block_manager.event_listener.layout_resolver.class%
        arguments:
            - @netgen_block_manager.layout_resolver
            - @netgen_block_manager.view.builder
            - @netgen_block_manager.templating.global_helper
        tags:
            - { name: kernel.event_subscriber }
