http_cache:
    ttl:
        default:
            block:
                max_age: 0
                shared_max_age: 300
                overwrite_headers: false
            layout:
                max_age: 0
                shared_max_age: 300
                overwrite_headers: false
    invalidation:
        enabled: "%kernel.debug%"
        default_strategy: ban
        strategies:
            ban:
                block:
                    tagger: netgen_block_manager.http_cache.block.ban.tagger
                    invalidator: netgen_block_manager.http_cache.block.ban.invalidator
                layout:
                    tagger: netgen_block_manager.http_cache.layout.ban.tagger
                    invalidator: netgen_block_manager.http_cache.layout.ban.invalidator
