parameters:
    netgen_block_manager.default.layouts:
        3_zones_a:
            name: '3 zones A'
            zones:
                top_left:
                    name: 'Top left'
                    allowed_blocks: ['title', 'paragraph']
                top_right:
                    name: 'Top right'
                bottom:
                    name: 'Bottom'
