layout_types:
    3_zones_a:
        name: '3 zones A'
        zones:
            top_left:
                name: 'Top left'
            top_right:
                name: 'Top right'
            bottom:
                name: 'Bottom'

    3_zones_b:
        name: '3 zones B'
        zones:
            top_left:
                name: 'Top left'
            top_right:
                name: 'Top right'
            bottom:
                name: 'Bottom'
