parameters:
    netgen_block_manager.normalizer.block.class: Netgen\BlockManager\Serializer\Normalizer\BlockNormalizer
    netgen_block_manager.normalizer.layout.class: Netgen\BlockManager\Serializer\Normalizer\LayoutNormalizer
    netgen_block_manager.normalizer.exception.class: Netgen\BlockManager\Serializer\Normalizer\ExceptionNormalizer

services:
    netgen_block_manager.normalizer.block:
        class: "%netgen_block_manager.normalizer.block.class%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.layout:
        class: "%netgen_block_manager.normalizer.layout.class%"
        arguments:
            - "@netgen_block_manager.configuration"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: "%netgen_block_manager.normalizer.exception.class%"
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: serializer.normalizer }
