parameters:
    netgen_block_manager.param_converter.block.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\BlockParamConverter
    netgen_block_manager.param_converter.layout.class: Netgen\Bundle\BlockManagerBundle\ParamConverter\LayoutParamConverter

services:
    netgen_block_manager.param_converter.block:
        class: %netgen_block_manager.param_converter.block.class%
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: request.param_converter }

    netgen_block_manager.param_converter.layout:
        class: %netgen_block_manager.param_converter.layout.class%
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: request.param_converter }
