query_types:
    ezcontent_search:
        name: 'eZ Publish'
        forms:
            full:
                type: ~
        defaults:
            parameters:
                parent_location_id: 2
                sort_direction: descending
                sort_type: date_published
                offset: 0
                query_type: list
