query_types:
    ezcontent_search:
        name: 'eZ Publish'
        forms:
            full:
                type: ~
        defaults:
            parameters:
                parent_location_id: 2
                content_types: [ng_news, ng_article]
