parameters:
    netgen_block_manager.registry.block_definition.array_based.class: Netgen\BlockManager\Registry\BlockDefinitionRegistry\ArrayBased

services:
    netgen_block_manager.registry.block_definition.array_based:
        class: %netgen_block_manager.registry.block_definition.array_based.class%

    netgen_block_manager.registry.block_definition:
        alias: netgen_block_manager.registry.block_definition.array_based
