_ngbm_api_v1:
    resource: "routing/api_v1.yml"
    prefix: /api/v1

_ngbm_admin:
    resource: "@NetgenBlockManagerAdminBundle/Resources/config/routing/admin.yml"

_ngbm_app:
    resource: "@NetgenBlockManagerAdminBundle/Resources/config/routing/app.yml"

ngbm_ajax_block:
    path: /ajax/block/{blockId}/{locale}/{collectionIdentifier}
    methods: [GET]
    defaults:
        _controller: "ngbm_ajax_block"
        _ngbm_status: published

ngbm_root:
    path: /
