netgen_block_manager_api_v1:
    resource: "routing/api_v1.yml"
    prefix: /api/v1

_netgen_block_manager_admin:
    resource: "@NetgenBlockManagerAdminUIBundle/Resources/config/routing/admin.yml"
    prefix: /admin

netgen_block_manager_app:
    resource: "@NetgenBlockManagerAdminUIBundle/Resources/config/routing/app.yml"
    prefix: /app
