_ngbm_api_v1:
    resource: "routing/api_v1.yml"
    prefix: /api/v1

_ngbm_admin:
    resource: "@NetgenBlockManagerAdminBundle/Resources/config/routing/admin.yml"
    prefix: /admin

_ngbm_app:
    resource: "@NetgenBlockManagerAdminBundle/Resources/config/routing/app.yml"
    prefix: /app
