netgen_block_manager_rest_v1_load_block:
    path: /block/{blockId}
    defaults:
        _controller: netgen_block_manager.controller.rest.block:getBlock

netgen_block_manager_rest_v1_load_layout:
    path: /layout/{layoutId}
    defaults:
        _controller: netgen_block_manager.controller.rest.layout:getLayout
