parameters:
    netgen_block_manager.serializer_handler.base.class: Netgen\BlockManager\SerializerHandler\SerializerHandler
    netgen_block_manager.serializer_handler.json.block.class: Netgen\BlockManager\SerializerHandler\Json\BlockSerializerHandler
    netgen_block_manager.serializer_handler.json.block_view.class: Netgen\BlockManager\SerializerHandler\Json\BlockViewSerializerHandler
    netgen_block_manager.serializer_handler.json.layout.class: Netgen\BlockManager\SerializerHandler\Json\LayoutSerializerHandler
    netgen_block_manager.serializer_handler.json.layout_view.class: Netgen\BlockManager\SerializerHandler\Json\LayoutViewSerializerHandler

services:
    netgen_block_manager.serializer_handler.json.block:
        class: %netgen_block_manager.serializer_handler.json.block.class%
        arguments:
            - %netgen_block_manager.default.blocks%
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer_handler.json.block_view:
        class: %netgen_block_manager.serializer_handler.json.block_view.class%
        parent: netgen_block_manager.serializer_handler.json.block
        arguments:
            - @netgen_block_manager.view.renderer
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer_handler.json.layout:
        class: %netgen_block_manager.serializer_handler.json.layout.class%
        arguments:
            - %netgen_block_manager.default.layouts%
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer_handler.json.layout_view:
        class: %netgen_block_manager.serializer_handler.json.layout_view.class%
        parent: netgen_block_manager.serializer_handler.json.layout
        arguments:
            - @netgen_block_manager.view.renderer
        tags:
            - { name: jms_serializer.subscribing_handler }
