parameters:
    netgen_block_manager.serializer.block.class: Netgen\BlockManager\Serializer\BlockSerializer
    netgen_block_manager.serializer.block_view.class: Netgen\BlockManager\Serializer\BlockViewSerializer
    netgen_block_manager.serializer.layout.class: Netgen\BlockManager\Serializer\LayoutSerializer
    netgen_block_manager.serializer.layout_view.class: Netgen\BlockManager\Serializer\LayoutViewSerializer

services:
    netgen_block_manager.serializer.block:
        class: %netgen_block_manager.serializer.block.class%
        arguments:
            - %netgen_block_manager.default.blocks%
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer.block_view:
        class: %netgen_block_manager.serializer.block_view.class%
        parent: netgen_block_manager.serializer.block
        arguments:
            - @netgen_block_manager.view.renderer
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer.layout:
        class: %netgen_block_manager.serializer.layout.class%
        arguments:
            - %netgen_block_manager.default.layouts%
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer.layout_view:
        class: %netgen_block_manager.serializer.layout_view.class%
        parent: netgen_block_manager.serializer.layout
        arguments:
            - @netgen_block_manager.view.renderer
        tags:
            - { name: jms_serializer.subscribing_handler }
