sources:
    dynamic:
        name: 'Dynamic source'
        query_type: ezcontent_search
        default_parameters:
            parent_location_id: 2
            content_types: [ng_news, ng_article]
