parameters:
    netgen_block_manager.validator.block_view_type.class: Netgen\BlockManager\Validator\BlockViewTypeValidator
    netgen_block_manager.validator.block_definition.class: Netgen\BlockManager\Validator\BlockDefinitionValidator
    netgen_block_manager.validator.layout.class: Netgen\BlockManager\Validator\LayoutValidator
    netgen_block_manager.validator.layout_zones.class: Netgen\BlockManager\Validator\LayoutZonesValidator

services:
    netgen_block_manager.validator.block_view_type:
        class: "%netgen_block_manager.validator.block_view_type.class%"
        arguments:
            - "@netgen_block_manager.configuration"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_view_type }

    netgen_block_manager.validator.block_definition:
        class: "%netgen_block_manager.validator.block_definition.class%"
        arguments:
            - "@netgen_block_manager.block_definition.registry"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_block_definition }

    netgen_block_manager.validator.layout:
        class: "%netgen_block_manager.validator.layout.class%"
        arguments:
            - "@netgen_block_manager.configuration"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_layout }

    netgen_block_manager.validator.layout_zones:
        class: "%netgen_block_manager.validator.layout_zones.class%"
        arguments:
            - "@netgen_block_manager.configuration"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_layout_zones }
