parameters:
    netgen_block_manager.layout.resolver.condition_type.route_parameter.class: Netgen\BlockManager\Layout\Resolver\ConditionType\RouteParameter

services:
    netgen_block_manager.layout.resolver.condition_type.route_parameter:
        class: "%netgen_block_manager.layout.resolver.condition_type.route_parameter.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type, priority: 0 }
