services:
    netgen_block_manager.layout.resolver.condition_type.route_parameter:
        class: Netgen\BlockManager\Layout\Resolver\ConditionType\RouteParameter
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }

    netgen_block_manager.layout.resolver.condition_type.query_parameter:
        class: Netgen\BlockManager\Layout\Resolver\ConditionType\QueryParameter
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }

    netgen_block_manager.layout.resolver.condition_type.exception:
        class: Netgen\BlockManager\Layout\Resolver\ConditionType\Exception
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }
