services:
    # Forms

    netgen_block_manager.layout.resolver.form.target_type:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType
        # public: false
        arguments:
            - []
        tags:
            - { name: form.type }

    netgen_block_manager.layout.resolver.form.condition_type:
        class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType
        # public: false
        arguments:
            - []
        tags:
            - { name: form.type }

    # Mappers

    netgen_block_manager.layout.resolver.form.target_type.mapper.route:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\Route
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: route }

    netgen_block_manager.layout.resolver.form.target_type.mapper.route_prefix:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\RoutePrefix
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: route_prefix }

    netgen_block_manager.layout.resolver.form.target_type.mapper.path_info:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\PathInfo
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: path_info }

    netgen_block_manager.layout.resolver.form.target_type.mapper.path_info_prefix:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\PathInfoPrefix
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: path_info_prefix }

    netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\RequestUri
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: request_uri }

    netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri_prefix:
        class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\RequestUriPrefix
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: request_uri_prefix }

    netgen_block_manager.layout.resolver.form.condition_type.mapper.route_parameter:
        class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType\Mapper\RouteParameter
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: route_parameter }

    netgen_block_manager.layout.resolver.form.condition_type.mapper.query_parameter:
        class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType\Mapper\QueryParameter
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: query_parameter }

    netgen_block_manager.layout.resolver.form.condition_type.mapper.exception:
        class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType\Mapper\Exception
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: exception }
