parameters:
    netgen_block_manager.layout.resolver.form.target_type.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType
    netgen_block_manager.layout.resolver.form.condition_type.class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType

    netgen_block_manager.layout.resolver.form.target_type.mapper.route.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\Route
    netgen_block_manager.layout.resolver.form.target_type.mapper.route_prefix.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\RoutePrefix
    netgen_block_manager.layout.resolver.form.target_type.mapper.path_info.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\PathInfo
    netgen_block_manager.layout.resolver.form.target_type.mapper.path_info_prefix.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\PathInfoPrefix
    netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\RequestUri
    netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri_prefix.class: Netgen\BlockManager\Layout\Resolver\Form\TargetType\Mapper\RequestUriPrefix

    netgen_block_manager.layout.resolver.form.condition_type.mapper.route_parameter.class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType\Mapper\RouteParameter

services:
    # Forms

    netgen_block_manager.layout.resolver.form.target_type:
        class: "%netgen_block_manager.layout.resolver.form.target_type.class%"
        arguments:
            - []
        tags:
            - { name: form.type }

    netgen_block_manager.layout.resolver.form.condition_type:
        class: "%netgen_block_manager.layout.resolver.form.condition_type.class%"
        arguments:
            - []
        tags:
            - { name: form.type }

    # Mappers

    netgen_block_manager.layout.resolver.form.target_type.mapper.route:
        class: "%netgen_block_manager.layout.resolver.form.target_type.mapper.route.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: route }
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: route_prefix }

    netgen_block_manager.layout.resolver.form.target_type.mapper.route_prefix:
        class: "%netgen_block_manager.layout.resolver.form.target_type.mapper.route_prefix.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: route_prefix }

    netgen_block_manager.layout.resolver.form.target_type.mapper.path_info:
        class: "%netgen_block_manager.layout.resolver.form.target_type.mapper.path_info.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: path_info }

    netgen_block_manager.layout.resolver.form.target_type.mapper.path_info_prefix:
        class: "%netgen_block_manager.layout.resolver.form.target_type.mapper.path_info_prefix.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: path_info_prefix }

    netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri:
        class: "%netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: request_uri }

    netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri_prefix:
        class: "%netgen_block_manager.layout.resolver.form.target_type.mapper.request_uri_prefix.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, identifier: request_uri_prefix }

    netgen_block_manager.layout.resolver.form.condition_type.mapper.route_parameter:
        class: "%netgen_block_manager.layout.resolver.form.condition_type.mapper.route_parameter.class%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, identifier: route_parameter }
