parameters:
    netgen_block_manager.layout.resolver.form.condition_type.class: Netgen\BlockManager\Layout\Resolver\Form\ConditionType

services:
    netgen_block_manager.layout.resolver.form.condition_type:
        class: "%netgen_block_manager.layout.resolver.form.condition_type.class%"
        arguments:
            - []
        tags:
            - { name: form.type }
