parameters:
    netgen_block_manager.layout.resolver.class: Netgen\BlockManager\Layout\Resolver\LayoutResolver

services:
    netgen_block_manager.layout.resolver:
        class: "%netgen_block_manager.layout.resolver.class%"
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - []
            - []
