services:
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Route
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: route }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route_prefix:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\RoutePrefix
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: route_prefix }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\PathInfo
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: path_info }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info_prefix:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\PathInfoPrefix
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: path_info_prefix }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\RequestUri
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: request_uri }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri_prefix:
        class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\RequestUriPrefix
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: request_uri_prefix }
