parameters:
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Route
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route_prefix.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\RoutePrefix
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\PathInfo
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info_prefix.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\PathInfoPrefix
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\RequestUri
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri_prefix.class: Netgen\BlockManager\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\RequestUriPrefix

services:
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: route }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route_prefix:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.route_prefix.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: route_prefix }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: path_info }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info_prefix:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.path_info_prefix.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: path_info_prefix }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: request_uri }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri_prefix:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.request_uri_prefix.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: request_uri_prefix }
