assets:
    packages:
        ngbm_admin_css:
            base_path: '/bundles/netgenblockmanageradmin/css'
            # version: '%ngbm_admin.asset.version%'
            version: ~
            version_format: 'v%%2$s/%%1$s'
        ngbm_admin_js:
            base_path: '/bundles/netgenblockmanageradmin/js'
            # version: '%ngbm_admin.asset.version%'
            version: ~
            version_format: 'v%%2$s/%%1$s'
        ngbm_admin_images:
            base_path: '/bundles/netgenblockmanageradmin/images'
            version: ~
            version_format: ~
        ngbm_admin_vendor:
            base_path: '/bundles/netgenblockmanageradmin/vendor'
            version: ~
            version_format: ~
        ngbm_admin:
            base_path: '/bundles/netgenblockmanageradmin'
            version: ~
            version_format: ~
