netgen_block_manager_api_v1_load_block_named_collections:
    path: /blocks/{block_id}/collections/named
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadNamedCollections"

netgen_block_manager_api_v1_load_block_collections:
    path: /blocks/{block_id}/collections
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollections"

netgen_block_manager_api_v1_load_block_collection:
    path: /blocks/{block_id}/collections/{collection_id}
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollection"

netgen_block_manager_api_v1_load_block_collection_items:
    path: /blocks/{block_id}/collections/{collection_id}/items
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollectionItems"

netgen_block_manager_api_v1_load_block_collection_queries:
    path: /blocks/{block_id}/collections/{collection_id}/queries
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollectionQueries"

netgen_block_manager_api_v1_load_block_collection_item:
    path: /blocks/{block_id}/collections/{collection_id}/items/{item_id}
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadItem"

netgen_block_manager_api_v1_add_block_collection_item:
    path: /blocks/{block_id}/collections/{collection_id}/items
    methods: [POST]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:addItem"

netgen_block_manager_api_v1_move_block_collection_item:
    path: /blocks/{block_id}/collections/{collection_id}/items/{item_id}/move
    methods: [PATCH]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:moveItem"

netgen_block_manager_api_v1_delete_block_collection_item:
    path: /blocks/{block_id}/collections/{collection_id}/items/{item_id}
    methods: [DELETE]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:deleteItem"

netgen_block_manager_api_v1_load_block_collection_query:
    path: /blocks/{block_id}/collections/{collection_id}/queries/{query_id}
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadQuery"

netgen_block_manager_api_v1_edit_query:
    path: /collections/queries/{query_id}/edit/full
    methods: [GET, PATCH]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:editQuery"
