netgen_block_manager_api_v1_block_load:
    path: /blocks/{blockId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:view"

netgen_block_manager_api_v1_block_collections:
    path: /blocks/{blockId}/collections
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:loadCollectionReferences"

netgen_block_manager_api_v1_block_collection_result:
    path: /blocks/{blockId}/collections/{collectionIdentifier}/result
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:loadCollectionResult"

netgen_block_manager_api_v1_block_collection_change_type:
    path: /blocks/{blockId}/collections/{collectionIdentifier}/change_type
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:changeCollectionType"

netgen_block_manager_api_v1_block_create:
    path: /blocks
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:create"

netgen_block_manager_api_v1_block_move:
    path: /blocks/{blockId}/move
    methods: [PATCH]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:move"

netgen_block_manager_api_v1_block_form:
    path: /blocks/{blockId}/form/{formName}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:form"

netgen_block_manager_api_v1_block_restore:
    path: /blocks/{blockId}/restore
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:restore"

netgen_block_manager_api_v1_block_delete:
    path: /blocks/{blockId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:delete"
