ngbm_api_v1_block_collections_load:
    path: /blocks/{blockId}/collections/{collectionIdentifier}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block_collection:load"

ngbm_api_v1_block_collections_references:
    path: /blocks/{blockId}/collections
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollectionReferences"

ngbm_api_v1_block_collections_result:
    path: /blocks/{blockId}/collections/{collectionIdentifier}/result
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollectionResult"

ngbm_api_v1_block_collections_change_type:
    path: /blocks/{blockId}/collections/{collectionIdentifier}/change_type
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block_collection:changeCollectionType"
