netgen_block_manager_api_v1_load_block_named_collections:
    path: /blocks/{blockId}/collections/named
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadNamedCollections"

netgen_block_manager_api_v1_load_block_collections:
    path: /blocks/{blockId}/collections
    methods: [GET]
    defaults:
        _ngbm_value_status: 0
        _controller: "netgen_block_manager.controller.api.v1.block_collection:loadCollections"
