netgen_block_manager_api_v1_load_block:
    path: /blocks/{blockId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:view"

netgen_block_manager_api_v1_load_block_collections:
    path: /blocks/{blockId}/collections
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:loadCollections"

netgen_block_manager_api_v1_create_block:
    path: /blocks
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:create"

netgen_block_manager_api_v1_edit_block:
    path: /blocks/{blockId}/edit
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:edit"

netgen_block_manager_api_v1_move_block:
    path: /blocks/{blockId}/move
    methods: [PATCH]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:move"

netgen_block_manager_api_v1_block_form:
    path: /blocks/{blockId}/form/{formName}
    methods: [GET, POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:form"

netgen_block_manager_api_v1_restore_block:
    path: /blocks/{blockId}/restore
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:restore"

netgen_block_manager_api_v1_delete_block:
    path: /blocks/{blockId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.block:delete"
