ngbm_api_v1_collections_load:
    path: /collections/{collectionId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:loadCollection"

ngbm_api_v1_collections_result:
    path: /collections/{collectionId}/result
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:loadCollectionResult"

ngbm_api_v1_collections_items:
    path: /collections/{collectionId}/items
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:loadCollectionItems"

ngbm_api_v1_collections_queries:
    path: /collections/{collectionId}/queries
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:loadCollectionQueries"

ngbm_api_v1_collections_load_item:
    path: /collections/items/{itemId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:loadItem"

ngbm_api_v1_collections_add_items:
    path: /collections/{collectionId}/items
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:addItems"

ngbm_api_v1_collections_move_item:
    path: /collections/items/{itemId}/move
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:moveItem"

ngbm_api_v1_collections_delete_item:
    path: /collections/items/{itemId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:deleteItem"

ngbm_api_v1_collections_load_query:
    path: /collections/queries/{queryId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:loadQuery"

ngbm_api_v1_collections_move_query:
    path: /collections/queries/{queryId}/move
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:moveQuery"

ngbm_api_v1_collections_delete:
    path: /collections/queries/{queryId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.collection:deleteQuery"
