netgen_block_manager_api_v1_load_named_collections:
    path: /collections/named
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.collection:loadNamedCollections"

netgen_block_manager_api_v1_load_collection:
    path: /collections/{collection_id}
    methods: [GET]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:load"

netgen_block_manager_api_v1_load_collection_items:
    path: /collections/{collection_id}/items
    methods: [GET]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:loadCollectionItems"

netgen_block_manager_api_v1_load_collection_queries:
    path: /collections/{collection_id}/queries
    methods: [GET]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:loadCollectionQueries"

netgen_block_manager_api_v1_create_collection:
    path: /collections
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.collection:create"

netgen_block_manager_api_v1_delete_collection:
    path: /collections/{collection_id}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.collection:delete"

netgen_block_manager_api_v1_load_item:
    path: /collections/items/{collection_item_id}
    methods: [GET]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:loadItem"

netgen_block_manager_api_v1_add_item:
    path: /collections/{collection_id}/items
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.collection:addItem"

netgen_block_manager_api_v1_move_item:
    path: /collections/items/{collection_item_id}/move
    methods: [PATCH]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:moveItem"

netgen_block_manager_api_v1_delete_item:
    path: /collections/items/{collection_item_id}
    methods: [DELETE]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:deleteItem"

netgen_block_manager_api_v1_load_query:
    path: /collections/queries/{collection_query_id}
    methods: [GET]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:loadQuery"

netgen_block_manager_api_v1_move_query:
    path: /collections/queries/{collection_query_id}/move
    methods: [PATCH]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:moveQuery"

netgen_block_manager_api_v1_delete_query:
    path: /collections/queries/{collection_query_id}
    methods: [DELETE]
    defaults:
        _ngbm_status: 1
        _controller: "netgen_block_manager.controller.api.collection:deleteQuery"
