ngbm_api_v1_config_config:
    path: /config
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.config:getConfig"

ngbm_api_v1_config_block_types:
    path: /config/block_types
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.config:getBlockTypes"

ngbm_api_v1_config_layout_types:
    path: /config/layout_types
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.config:getLayoutTypes"
