ngbm_api_v1_layouts_shared:
    path: /layouts/shared
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:loadSharedLayouts"

ngbm_api_v1_layouts_load:
    path: /layouts/{layoutId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:load"

ngbm_api_v1_layouts_blocks:
    path: /layouts/{layoutId}/{locale}/blocks
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:viewLayoutBlocks"

ngbm_api_v1_layouts_zone_blocks:
    path: /layouts/{layoutId}/{locale}/zones/{zoneIdentifier}/blocks
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:viewZoneBlocks"

ngbm_api_v1_layouts_zone_link:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:linkZone"
        _ngbm_status: draft

ngbm_api_v1_layouts_zone_unlink:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:unlinkZone"
        _ngbm_status: draft

ngbm_api_v1_layouts_create:
    path: /layouts
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:create"

ngbm_api_v1_layouts_copy:
    path: /layouts/{layoutId}/copy
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:copy"

ngbm_api_v1_layouts_change_type:
    path: /layouts/{layoutId}/change_type
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:changeType"
        _ngbm_status: draft

ngbm_api_v1_layouts_create_draft:
    path: /layouts/{layoutId}/draft
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:createDraft"
        _ngbm_status: published

ngbm_api_v1_layouts_discard_draft:
    path: /layouts/{layoutId}/draft
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:discardDraft"
        _ngbm_status: draft

ngbm_api_v1_layouts_publish:
    path: /layouts/{layoutId}/publish
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:publishDraft"
        _ngbm_status: draft

ngbm_api_v1_layouts_delete:
    path: /layouts/{layoutId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:delete"
        _ngbm_status: published
