netgen_block_manager_api_v1_layout_load:
    path: /layouts/{layoutId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:view"

netgen_block_manager_api_v1_layout_blocks:
    path: /layouts/{layoutId}/blocks
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:viewLayoutBlocks"

netgen_block_manager_api_v1_layout_create:
    path: /layouts
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:create"

netgen_block_manager_api_v1_layout_update:
    path: /layouts/{layoutId}
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:update"

netgen_block_manager_api_v1_layout_publish:
    path: /layouts/{layoutId}/publish
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:publish"
