ngbm_api_v1_layout_load:
    path: /layouts/{layoutId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:load"

ngbm_api_v1_layout_blocks:
    path: /layouts/{layoutId}/blocks
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:viewLayoutBlocks"

ngbm_api_v1_layout_zone_link:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:linkZone"

ngbm_api_v1_layout_zone_unlink:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:removeZoneLink"

ngbm_api_v1_layout_create:
    path: /layouts
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:create"

ngbm_api_v1_layout_update:
    path: /layouts/{layoutId}
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:update"

ngbm_api_v1_layout_create_draft:
    path: /layouts/{layoutId}/draft
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:createDraft"

ngbm_api_v1_layout_discard:
    path: /layouts/{layoutId}/discard
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:discard"

ngbm_api_v1_layout_publish:
    path: /layouts/{layoutId}/publish
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:publish"
