netgen_block_manager_api_v1_layout_resolver_rule_create:
    path: /layout_resolver/rules
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:createRule"

netgen_block_manager_api_v1_layout_resolver_rule_update:
    path: /layout_resolver/rules/{ruleId}
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:updateRule"

netgen_block_manager_api_v1_layout_resolver_rule_enable:
    path: /layout_resolver/rules/{ruleId}/enable
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:enableRule"

netgen_block_manager_api_v1_layout_resolver_rule_disable:
    path: /layout_resolver/rules/{ruleId}/disable
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:disableRule"

netgen_block_manager_api_v1_layout_resolver_rule_create_draft:
    path: /layout_resolver/rules/{ruleId}/draft
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:createRuleDraft"

netgen_block_manager_api_v1_layout_resolver_rule_discard:
    path: /layout_resolver/rules/{ruleId}/discard
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:discardRuleDraft"

netgen_block_manager_api_v1_layout_resolver_rule_publish:
    path: /layout_resolver/rules/{ruleId}/publish
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:publishRuleDraft"

netgen_block_manager_api_v1_layout_resolver_rule_delete:
    path: /layout_resolver/rules/{ruleId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:deleteRule"

netgen_block_manager_api_v1_layout_resolver_target_delete:
    path: /layout_resolver/targets/{targetId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:deleteTarget"

netgen_block_manager_api_v1_layout_resolver_condition_delete:
    path: /layout_resolver/conditions/{conditionId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout_resolver:deleteCondition"
