ngbm_api_v1_layouts_shard:
    path: /layouts/shared
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:loadSharedLayouts"

ngbm_api_v1_layouts_load:
    path: /layouts/{layoutId}
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:load"

ngbm_api_v1_layouts_blocks:
    path: /layouts/{layoutId}/blocks
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:viewLayoutBlocks"

ngbm_api_v1_layouts_zone_blocks:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/blocks
    methods: [GET]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:viewZoneBlocks"

ngbm_api_v1_layouts_zone_link:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:linkZone"

ngbm_api_v1_layouts_zone_unlink:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:unlinkZone"

ngbm_api_v1_layouts_create:
    path: /layouts
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:create"

ngbm_api_v1_layouts_update:
    path: /layouts/{layoutId}
    methods: [PATCH]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:update"

ngbm_api_v1_layouts_copy:
    path: /layouts/{layoutId}/copy
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:copy"

ngbm_api_v1_layouts_create_draft:
    path: /layouts/{layoutId}/draft
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:createDraft"

ngbm_api_v1_layouts_copy_draft:
    path: /layouts/{layoutId}/draft/copy
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:copyDraft"

ngbm_api_v1_layouts_discard_draft:
    path: /layouts/{layoutId}/draft
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:discardDraft"

ngbm_api_v1_layouts_publish:
    path: /layouts/{layoutId}/publish
    methods: [POST]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:publishDraft"

ngbm_api_v1_layouts_delete:
    path: /layouts/{layoutId}
    methods: [DELETE]
    defaults:
        _controller: "netgen_block_manager.controller.api.v1.layout:delete"
